server:
 port: 9999
 contextPath: /uaa
security:
 oauth2:
  client:
   scope: openid
   id: acme
  jwt.signingKey: secret
 user.password: password


# Let flyway recreate the DB if validation fails.
flyway.clean-on-validation-error : true

# DB
spring:
 datasource:
  url: jdbc:h2:mem:data_ref
#spring.datasource.url: jdbc:h2:tcp://localhost/~/java_data
  username: sa
  password:
  driverClassName: org.h2.Driver
  poolSize: 30

# JPA
#spring.jpa.hibernate.ddl-auto: create-drop
 jpa:
  properties.hibernate.search.default.indexBase : /tmp
  hibernate:
   ddl-auto: update
#spring.jpa.hibernate.ddl-auto: validate
   naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  database: H2
  show-sql: false
# hibernate search index configuration
  properties.hibernate.search.default.directory_provider : filesystem
#spring.jpa.properties.hibernate.search.default.indexBase : ${pfad}/tmp/index
 data:
  rest:
   return-body-on-update : true
   return-body-on-create : true

logging.level.org.springframework.security: DEBUG
