package de.muenchen.demo.service.services;

import de.muenchen.demo.service.gen.domain.AdresseExtern;
import de.muenchen.demo.service.gen.services.AdresseExternEventService;
import org.springframework.stereotype.Service;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by AdresseExternEventListener.
 */
@Service
public class AdresseExternEventServiceImpl implements AdresseExternEventService {
    // If you need access to the database you can autowire a Repository.
    // Repositories are generated into the package: .gen.rest
    //
    // @Autowired
    // <EntityName>Repository repo;

    @Override
    public void onAfterCreate(AdresseExtern entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeCreate(AdresseExtern entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeSave(AdresseExtern entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterSave(AdresseExtern entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkSave(AdresseExtern parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkSave(AdresseExtern parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkDelete(AdresseExtern parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeDelete(AdresseExtern entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterDelete(AdresseExtern entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkDelete(AdresseExtern parent, Object linked) {
        // Add your logic here.
    }
}
