package de.muenchen.demo.service.services;

import de.muenchen.demo.service.gen.domain.Adresse;
import de.muenchen.demo.service.gen.services.AdresseEventService;
import org.springframework.stereotype.Service;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by AdresseEventListener.
 */
@Service
public class AdresseEventServiceImpl implements AdresseEventService {
    // If you need access to the database you can autowire a Repository.
    // Repositories are generated into the package: .gen.rest
    //
    // @Autowired
    // <EntityName>Repository repo;

    @Override
    public void onAfterCreate(Adresse entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeCreate(Adresse entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeSave(Adresse entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterSave(Adresse entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkSave(Adresse parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkSave(Adresse parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkDelete(Adresse parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeDelete(Adresse entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterDelete(Adresse entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkDelete(Adresse parent, Object linked) {
        // Add your logic here.
    }
}
