package de.muenchen.demo.service.services;

import de.muenchen.demo.service.gen.domain.AdresseIntern;
import de.muenchen.demo.service.gen.services.AdresseInternEventService;
import org.springframework.stereotype.Service;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by AdresseInternEventListener.
 */
@Service
public class AdresseInternEventServiceImpl implements AdresseInternEventService {
    // If you need access to the database you can autowire a Repository.
    // Repositories are generated into the package: .gen.rest
    //
    // @Autowired
    // <EntityName>Repository repo;

    @Override
    public void onAfterCreate(AdresseIntern entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeCreate(AdresseIntern entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeSave(AdresseIntern entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterSave(AdresseIntern entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkSave(AdresseIntern parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkSave(AdresseIntern parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkDelete(AdresseIntern parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeDelete(AdresseIntern entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterDelete(AdresseIntern entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkDelete(AdresseIntern parent, Object linked) {
        // Add your logic here.
    }
}
