package de.muenchen.demo.service.services;

import de.muenchen.demo.service.gen.domain.Pass;
import de.muenchen.demo.service.gen.services.PassEventService;
import org.springframework.stereotype.Service;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by PassEventListener.
 */
@Service
public class PassEventServiceImpl implements PassEventService {
    // If you need access to the database you can autowire a Repository.
    // Repositories are generated into the package: .gen.rest
    //
    // @Autowired
    // <EntityName>Repository repo;

    @Override
    public void onAfterCreate(Pass entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeCreate(Pass entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeSave(Pass entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterSave(Pass entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkSave(Pass parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkSave(Pass parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkDelete(Pass parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeDelete(Pass entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterDelete(Pass entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkDelete(Pass parent, Object linked) {
        // Add your logic here.
    }
}
