package de.muenchen.demo.service.services;

import de.muenchen.demo.service.gen.domain.Sachbearbeiter;
import de.muenchen.demo.service.gen.services.SachbearbeiterEventService;
import org.springframework.stereotype.Service;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by SachbearbeiterEventListener.
 */
@Service
public class SachbearbeiterEventServiceImpl implements SachbearbeiterEventService {
    // If you need access to the database you can autowire a Repository.
    // Repositories are generated into the package: .gen.rest
    //
    // @Autowired
    // <EntityName>Repository repo;

    @Override
    public void onAfterCreate(Sachbearbeiter entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeCreate(Sachbearbeiter entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeSave(Sachbearbeiter entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterSave(Sachbearbeiter entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkSave(Sachbearbeiter parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkSave(Sachbearbeiter parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkDelete(Sachbearbeiter parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeDelete(Sachbearbeiter entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterDelete(Sachbearbeiter entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkDelete(Sachbearbeiter parent, Object linked) {
        // Add your logic here.
    }
}
