package de.muenchen.demo.service.services;

import de.muenchen.demo.service.gen.domain.Staatsangehoerigkeit;
import de.muenchen.demo.service.gen.services.StaatsangehoerigkeitEventService;
import org.springframework.stereotype.Service;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by StaatsangehoerigkeitEventListener.
 */
@Service
public class StaatsangehoerigkeitEventServiceImpl implements StaatsangehoerigkeitEventService {
    // If you need access to the database you can autowire a Repository.
    // Repositories are generated into the package: .gen.rest
    //
    // @Autowired
    // <EntityName>Repository repo;

    @Override
    public void onAfterCreate(Staatsangehoerigkeit entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeCreate(Staatsangehoerigkeit entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeSave(Staatsangehoerigkeit entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterSave(Staatsangehoerigkeit entity) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkSave(Staatsangehoerigkeit parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkSave(Staatsangehoerigkeit parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeLinkDelete(Staatsangehoerigkeit parent, Object linked) {
        // Add your logic here.
    }

    @Override
    public void onBeforeDelete(Staatsangehoerigkeit entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterDelete(Staatsangehoerigkeit entity) {
        // Add your logic here.
    }

    @Override
    public void onAfterLinkDelete(Staatsangehoerigkeit parent, Object linked) {
        // Add your logic here.
    }
}
