spring:
  profiles.active: local
# JPA
#spring.jpa.hibernate.ddl-auto: create-drop
  jpa:
    properties.hibernate.search.default.indexBase : /tmp
    hibernate:
      ddl-auto: update
#spring.jpa.hibernate.ddl-auto: validate
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
# hibernate search index configuration
    properties.hibernate.search.default.directory_provider : filesystem
#spring.jpa.properties.hibernate.search.default.indexBase : ${pfad}/tmp/index
  data:
    rest:
     return-body-on-update : true
     return-body-on-create : true

server:
 contextPath: /uaa
security:
 oauth2:
  client:
# see org.springframework.boot.autoconfigure.security.oauth2.OAuth2ClientProperties for more Informations
   scope: openid
   id: acme
#TODO Get a Keystore
  jwt.signingKey: secret


# Let flyway recreate the DB if validation fails.
flyway.clean-on-validation-error : true

logging.level.org.springframework.security: DEBUG

--- 
spring:
    profiles: docker
    #DB
    datasource:
        url: jdbc:h2:mem:data_ref
        username: sa
        password:
        driverClassName: org.h2.Driver
        poolSize: 30
    #JPA
    jpa:
        database: H2
--- 
spring:
    profiles: local
    #DB
    datasource:
        url: jdbc:h2:mem:data_ref
        username: sa
        password:
        driverClassName: org.h2.Driver
        poolSize: 30
    #JPA
    jpa:
        database: H2
--- 
spring:
    profiles: vm
    #DB
    datasource:
        url: jdbc:h2:mem:data_ref
        username: sa
        password:
        driverClassName: org.h2.Driver
        poolSize: 30
    #JPA
    jpa:
        database: H2

