# Service Info
spring:
  profiles:
    active: local

  #i18n
  messages:
      basename: message
      cache-seconds: -1
      encoding: UTF-8

  # Spring data rest
  data.rest:
      return-body-on-update : true
      return-body-on-create : true

server.tomcat.max-http-header-size: 32000

info.url: http://localhost:${service.port}/
service:
    info:
        oid: BUERGERVERWALTUNG-BUERGER
        name: Buerger
        version: v1.0

# Let flyway recreate the DB if validation fails.
flyway.clean-on-validation-error : true

logging.level.org.springframework.cloud.netflix.config : 'OFF'
logging.level.com.netflix.discovery : 'OFF'

#Wiremock
URL : http://localhost:8089/

# Security
security.oauth2.resource.userInfoUri: http://AUTHSERVICE/uaa/user
security.oauth2.resource.preferTokenInfo: false

---
spring:
    profiles: docker
---
spring:
    profiles: local
---
spring:
    profiles: vm

