package de.muenchen.vaadin.demo.api.util;

/**
 *
 * @author claus.straube
 */
public enum EventType {
    CREATE, UPDATE, SAVE, DELETE, READ, SELECT, SELECT2UPDATE, SELECT2READ, COPY, CANCEL, QUERY, QUERY_CHILD, SAVE_CHILD, RELEASE, RELEASE_PARENT, SAVE_AS_CHILD, ADD_SEARCHED_CHILD,SAVE_AS_PARTNER, ADD_PARTNER, QUERY_PARTNER
}
