debug: true

server:
 port: 9001

spring:
 aop:
  proxy-target-class: true

security:
 oauth2:
    client:
      #accessTokenUri: http://localhost:8080/oauth/token
      #userAuthorizationUri: http://localhost:8080/oauth/authorize
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize

      clientId: acme
#      clientSecret: acmesecret
    resource:
      #userInfoUri: http://localhost:8080/principal
      userInfoUri: http://localhost:9999/uaa/user
      jwt:
       verifierKey: secret

zuul:
  routes:
    buergers:
      path: /buergers/**
      url: http://localhost:8080/buergers
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    logout-server:
      path: /logout-server/**
      url: http://localhost:9999/uaa/logout

logging:
  level:
    org.springframework.security: DEBUG
