package de.muenchen.vaadin.guilib.security.services;

import de.muenchen.vaadin.demo.apilib.local.Authority_;
import org.springframework.hateoas.Link;

import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Service zum Verwalten von Authority_ aus der GUI heraus.
 */
public interface Authority_Service {
    Authority_ create(Authority_ authority);

    Authority_ update(Authority_ authority);

    boolean delete(Link link);
		
    List<Authority_> findAll();

    List<Authority_> findAll(Link relation);

    Optional<Authority_> findOne(Link link);

    List<Authority_> queryAuthority(String query);

    boolean setRelations(Link link, List<Link> relations);

    boolean setRelation(Link link, Link relation);
}
