package de.muenchen.vaadin.guilib.security.services;

import de.muenchen.vaadin.demo.apilib.local.Authority;
import org.springframework.hateoas.Link;

import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Service zum Verwalten von Authority_ aus der GUI heraus.
 */
public interface Authority_Service {
    Authority create(Authority authority);

    Authority update(Authority authority);

    boolean delete(Link link);
		
    List<Authority> findAll();

    List<Authority> findAll(Link relation);

    Optional<Authority> findOne(Link link);

    List<Authority> queryAuthority(String query);

    boolean setRelations(Link link, List<Link> relations);

    boolean setRelation(Link link, Link relation);
}
