package de.muenchen.vaadin.guilib.security.services;

import de.muenchen.vaadin.demo.apilib.local.Permission;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Permission_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Permission createPermissionFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Permission_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Permission> createPermissionsFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Permission_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Permission> createOptionalPermissionFallback(){
		return Optional.empty();
	}
	
}
