package de.muenchen.vaadin.guilib.security.services;

import de.muenchen.vaadin.demo.apilib.local.Permission;
import org.springframework.hateoas.Link;

import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Service zum Verwalten von Permission_ aus der GUI heraus.
 */
public interface Permission_Service {
    Permission create(Permission permission);

    Permission update(Permission permission);

    boolean delete(Link link);
		
    List<Permission> findAll();

    List<Permission> findAll(Link relation);

    Optional<Permission> findOne(Link link);

    List<Permission> queryPermission(String query);

    boolean setRelations(Link link, List<Link> relations);

    boolean setRelation(Link link, Link relation);
}
