package de.muenchen.vaadin.guilib.security.services;

import de.muenchen.vaadin.demo.apilib.local.User;
import org.springframework.hateoas.Link;

import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Service zum Verwalten von User_ aus der GUI heraus.
 */
public interface User_Service {
    User create(User user);

    User update(User user);

    boolean delete(Link link);
		
    List<User> findAll();

    List<User> findAll(Link relation);

    Optional<User> findOne(Link link);

    List<User> queryUser(String query);

    boolean setRelations(Link link, List<Link> relations);

    boolean setRelation(Link link, Link relation);
}
