package de.muenchen.vaadin.guilib.security.services;


import de.muenchen.vaadin.demo.apilib.local.User;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class User_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen User_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static User createUserFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von User_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<User> createUsersFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von User_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<User> createOptionalUserFallback(){
		return Optional.empty();
	}
	
}
