package de.muenchen.vaadin.guilib.security.services;

import de.muenchen.vaadin.demo.apilib.local.User_;
import org.springframework.hateoas.Link;

import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Service zum Verwalten von User_ aus der GUI heraus.
 */
public interface User_Service {
    User_ create(User_ user);

    User_ update(User_ user);

    boolean delete(Link link);
		
    List<User_> findAll();

    List<User_> findAll(Link relation);

    Optional<User_> findOne(Link link);

    List<User_> queryUser(String query);

    boolean setRelations(Link link, List<Link> relations);

    boolean setRelation(Link link, Link relation);
}
