package de.muenchen.auth.services;

import de.muenchen.auth.entities.Permission;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Provides methods to alter resources before being sent to a client.
 */
public interface PermissionResourceService {
    /**
     * Process a resource. You can add links and alter the entity itself.
     */
    Resource<Permission> process(Resource<Permission> resource);
}
