package de.muenchen.vaadin.demo.apilib.hateoas;


import de.muenchen.vaadin.demo.apilib.domain.Authority_DTO;
import de.muenchen.vaadin.demo.apilib.local.Authority_;
import de.muenchen.vaadin.demo.apilib.rest.Authority_Resource;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Authority_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Authority_ toBean(Resource<Authority_DTO> resource) {

		Authority_DTO authorityDTO = resource.getContent();
		Authority_ bean = new Authority_();
		bean.setAuthority(authorityDTO.getAuthority());
		bean.add(resource.getLinks());
		return bean;
	}
	

	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Authority_Resource toResource(Authority_ bean) {
		Authority_DTO authorityDTO = new Authority_DTO();
		authorityDTO.setAuthority(bean.getAuthority());
		return new Authority_Resource(authorityDTO, bean.getLinks());
	}
}
