package de.muenchen.vaadin.demo.apilib.hateoas;


import de.muenchen.vaadin.demo.apilib.domain.Permission_DTO;
import de.muenchen.vaadin.demo.apilib.local.Permission;
import de.muenchen.vaadin.demo.apilib.rest.Permission_Resource;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Permission toBean(Resource<Permission_DTO> resource) {

		Permission_DTO permissionDTO = resource.getContent();
		Permission bean = new Permission();
		bean.setPermission(permissionDTO.getPermission());
		bean.add(resource.getLinks());
		return bean;
	}
	

	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Permission_Resource toResource(Permission bean) {
		Permission_DTO permissionDTO = new Permission_DTO();
		permissionDTO.setPermission(bean.getPermission());
		return new Permission_Resource(permissionDTO, bean.getLinks());
	}
}
