package de.muenchen.vaadin.demo.apilib.hateoas;

import de.muenchen.vaadin.demo.apilib.domain.User_DTO;
import de.muenchen.vaadin.demo.apilib.local.User_;
import de.muenchen.vaadin.demo.apilib.rest.User_Resource;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class User_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public User_ toBean(Resource<User_DTO> resource) {

		User_DTO userDTO = resource.getContent();
		User_ bean = new User_();
		bean.setUsername(userDTO.getUsername());
		bean.setForname(userDTO.getForname());
		bean.setSurname(userDTO.getSurname());
		bean.setBirthdate(userDTO.getBirthdate());
		bean.setEmail(userDTO.getEmail());
		bean.setUserEnabled(userDTO.getUserEnabled());
		bean.add(resource.getLinks());
		return bean;
	}
	

	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public User_Resource toResource(User_ bean) {
		User_DTO userDTO = new User_DTO();
		userDTO.setUsername(bean.getUsername());
		userDTO.setForname(bean.getForname());
		userDTO.setSurname(bean.getSurname());
		userDTO.setBirthdate(bean.getBirthdate());
		userDTO.setEmail(bean.getEmail());
		userDTO.setUserEnabled(bean.getUserEnabled());
		return new User_Resource(userDTO, bean.getLinks());
	}
}
