
# Service Info
service.info.oid: EWO
service.info.name: Einwohnerwesen
service.info.version: v1.0 

#
management.address: 127.0.0.1
endpoints.shutdown.enabled: true

#i18n
spring.messages.basename: messages
spring.messages.cache-seconds: -1
spring.messages.encoding: UTF-8

# Let flyway recreate the DB if validation fails.
flyway.clean-on-validation-error : true

# DB
spring.datasource.url: jdbc:h2:mem:data_ref
#spring.datasource.url: jdbc:h2:tcp://localhost/~/java_data
spring.datasource.username: sa
spring.datasource.password:
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.poolSize: 30

# JPA
#spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.hibernate.ddl-auto: update
#spring.jpa.hibernate.ddl-auto: validate
spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.database: H2
spring.jpa.show-sql: false
# hibernate search index configuration 
spring.jpa.properties.hibernate.search.default.directory_provider : filesystem
#spring.jpa.properties.hibernate.search.default.indexBase : ${pfad}/tmp/index
spring.data.rest.return-body-on-update : true
spring.data.rest.return-body-on-create : true
spring.jpa.properties.hibernate.search.default.indexBase : /tmp

logging.level.org.springframework.cloud.netflix.config : 'OFF'
logging.level.com.netflix.discovery : 'OFF'


#Wiremock
URL : http://localhost:8089/

#pfad :/home/praktikant.tmar
#pfad :/home/claus.straube
pfad : /home/maximilian.zollbrecht

# Basis URL 
info.url: http://localhost:8080/
service.token.url: ${info.url}oauth/token

# Security
#security.basic.enabled:false
security.oauth2.client.id : acme
#security.oauth2.client.access-token-validity-seconds:10
#security.oauth2.client.scope:scope



