package de.muenchen.kvr.buergerverwaltung.buerger.client.local;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
import java.util.stream.Stream;

import javax.validation.constraints.NotNull;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.AdresseIntern_;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.AdresseExtern_;
import org.springframework.hateoas.ResourceSupport;
/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Adresse_ extends ResourceSupport {
	
	private AdresseIntern_ interneAdresse;
	
	private AdresseExtern_ externeAdresse;
	
	
	/**
     * Create a new Adresse_ with the .
     *
     */
    public Adresse_() {
    }
	
	// Getters and Setters
	public AdresseIntern_ getInterneAdresse(){
		return interneAdresse;
	}
	public void setInterneAdresse(AdresseIntern_ value){
		this.interneAdresse = value;
	}
	
	public AdresseExtern_ getExterneAdresse(){
		return externeAdresse;
	}
	public void setExterneAdresse(AdresseExtern_ value){
		this.externeAdresse = value;
	}
	
	 /**
      * A simple Enum for all the Fields of this Adresse_.
      * <p>
      *     You can use {@link Field#name()} for the String.
      * </p>
      */
	public enum Field {
        ;

        private final boolean field;

        Field() {
			this(true);
		}

		Field(boolean field) {
			this.field = field;
		}

		public boolean isField() {
			return field;
		}

		public static String[] getProperties() {
			return Stream.of(values()).filter(Field::isField).map(Field::name).toArray(String[]::new);
		}
	}
	
	 /**
	  * A simple Enum for all the Relations ({@link Adresse_#getLink(String)} of the Adresse_.
	  * <p>
	  *     You can use {@link Rel#name()} for the String.
	  * </p>
	  */
	 public enum Rel {
	 	;
    }
	
	@Override
	public String toString(){
		String s = "";
		return s;
	}
}
