package de.muenchen.kvr.buergerverwaltung.buerger.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Adresse_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Adresse_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Adresse_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Adresse_ createAdresseFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Adresse_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Adresse_> createAdressesFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Adresse_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Adresse_> createOptionalAdresseFallback(){
		return Optional.empty();
	}
	
}
