package de.muenchen.kvr.buergerverwaltung.buerger.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Pass_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Pass_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Pass_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Pass_ createPassFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Pass_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Pass_> createPasssFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Pass_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Pass_> createOptionalPassFallback(){
		return Optional.empty();
	}
	
}
