package de.muenchen.vaadin.demo.apilib.domain;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_DTO extends BaseEntity {
	
		private String permission;
		
		// Getters and Setters
		public String getPermission(){
			return permission;
		}
		
		public void setPermission(String permission){
			this.permission = permission;
		}
		
		@Override
		public String toString() {
		   	return String.format("%s = {\"permission\": \"%s\"}", getClass(),
		   		this.permission);
		}
	}
