package de.muenchen.vaadin.demo.apilib.domain;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class User_DTO extends BaseEntity {
	
		private String username;
		
		private String forname;
		
		private String surname;
		
		private java.util.Date birthdate;
		
		private String email;
		
		private boolean userEnabled;
		
		// Getters and Setters
		public String getUsername(){
			return username;
		}
		
		public void setUsername(String username){
			this.username = username;
		}
		
		public String getForname(){
			return forname;
		}
		
		public void setForname(String forname){
			this.forname = forname;
		}
		
		public String getSurname(){
			return surname;
		}
		
		public void setSurname(String surname){
			this.surname = surname;
		}
		
		public java.util.Date getBirthdate(){
			return birthdate;
		}
		
		public void setBirthdate(java.util.Date birthdate){
			this.birthdate = birthdate;
		}
		
		public String getEmail(){
			return email;
		}
		
		public void setEmail(String email){
			this.email = email;
		}
		
		public boolean getUserEnabled(){
			return userEnabled;
		}
		
		public void setUserEnabled(boolean userEnabled){
			this.userEnabled = userEnabled;
		}
		
		@Override
		public String toString() {
		   	return String.format("%s = {\"username\": \"%s\", \"forname\": \"%s\", \"surname\": \"%s\", \"birthdate\": \"%s\", \"email\": \"%s\", \"userEnabled\": \"%s\"}", getClass(),
		   		this.username,
		   		this.forname,
		   		this.surname,
		   		this.birthdate,
		   		this.email,
		   		this.userEnabled);
		}
	}
