package de.muenchen.kvr.buergerverwaltung.buerger.client.hateoas;

import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.Adresse_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Adresse_;
import de.muenchen.kvr.buergerverwaltung.buerger.client.rest.Adresse_Resource;
import org.springframework.hateoas.Resource;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Adresse_Assembler {


	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param resource the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Adresse_ toBean(Resource<Adresse_DTO> resource) {
		Adresse_DTO adresseDTO = resource.getContent();
		Adresse_ bean = new Adresse_();		
		bean.setInterneAdresse(new AdresseIntern_Assembler().toBean(adresseDTO.getInterneAdresse()));
		bean.setExterneAdresse(new AdresseExtern_Assembler().toBean(adresseDTO.getExterneAdresse()));
		bean.add(resource.getLinks());
		
		return bean;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Adresse_Resource toResource(Adresse_ bean) {
		Adresse_DTO adresseDTO = new Adresse_DTO();
		adresseDTO.setInterneAdresse(new AdresseIntern_Assembler().toDTO(bean.getInterneAdresse()));
		adresseDTO.setExterneAdresse(new AdresseExtern_Assembler().toDTO(bean.getExterneAdresse()));
		return new Adresse_Resource(adresseDTO, bean.getLinks());
	}
}
