package de.muenchen.kvr.buergerverwaltung.buerger.client.hateoas;

import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.AdresseExtern_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.AdresseExtern_;
import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.AdresseExtern_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.AdresseExtern_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class AdresseExtern_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param adresseExternDTO the REST DTO Resource
	 * @return the local Object Representation
	 */
	public AdresseExtern_ toBean(AdresseExtern_DTO adresseExternDTO) {
		AdresseExtern_ bean = new AdresseExtern_();
		bean.setStrasse(adresseExternDTO.getStrasse());
		bean.setHausnummer(adresseExternDTO.getHausnummer());
		bean.setPlz(adresseExternDTO.getPlz());
		bean.setOrt(adresseExternDTO.getOrt());
		return bean;
	}
	
	private AdresseExtern_ toAdresseExternBean(AdresseExtern_DTO adresseExternDTO) {
		AdresseExtern_ adresseExtern = new AdresseExtern_();
		adresseExtern.setStrasse(adresseExternDTO.getStrasse());
		adresseExtern.setHausnummer(adresseExternDTO.getHausnummer());
		adresseExtern.setPlz(adresseExternDTO.getPlz());
		adresseExtern.setOrt(adresseExternDTO.getOrt());
		return adresseExtern;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public AdresseExtern_DTO toDTO(AdresseExtern_ bean) {
		AdresseExtern_DTO adresseExternDTO = new AdresseExtern_DTO();
		adresseExternDTO.setStrasse(bean.getStrasse());
		adresseExternDTO.setHausnummer(bean.getHausnummer());
		adresseExternDTO.setPlz(bean.getPlz());
		adresseExternDTO.setOrt(bean.getOrt());
		return adresseExternDTO;
	}
}
