package de.muenchen.kvr.buergerverwaltung.buerger.client.hateoas;

import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.AdresseIntern_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.AdresseIntern_;
import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.AdresseIntern_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.AdresseIntern_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class AdresseIntern_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param adresseInternDTO the REST DTO Resource
	 * @return the local Object Representation
	 */
	public AdresseIntern_ toBean(AdresseIntern_DTO adresseInternDTO) {
		AdresseIntern_ bean = new AdresseIntern_();		bean.setStrassenSchluessel(adresseInternDTO.getStrassenSchluessel());
		bean.setHausnummer(adresseInternDTO.getHausnummer());
		return bean;
	}
	
	private AdresseIntern_ toAdresseInternBean(AdresseIntern_DTO adresseInternDTO) {
		AdresseIntern_ adresseIntern = new AdresseIntern_();
		adresseIntern.setStrassenSchluessel(adresseInternDTO.getStrassenSchluessel());
		adresseIntern.setHausnummer(adresseInternDTO.getHausnummer());
		return adresseIntern;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public AdresseIntern_DTO toDTO(AdresseIntern_ bean) {
		AdresseIntern_DTO adresseInternDTO = new AdresseIntern_DTO();
		adresseInternDTO.setStrassenSchluessel(bean.getStrassenSchluessel());
		adresseInternDTO.setHausnummer(bean.getHausnummer());
		return adresseInternDTO;
	}
}
