package de.muenchen.kvr.buergerverwaltung.buerger.client.hateoas;

import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.Adresse_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Adresse_;
import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.Adresse_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Adresse_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Adresse_Assembler {

	/**
	 * Transform the Resource (from the REST Server) to the local object representation.
	 *
	 * @param adresseDTO the REST DTO Resource
	 * @return the local Object Representation
	 */
	public Adresse_ toBean(Adresse_DTO adresseDTO) {
		Adresse_ bean = new Adresse_();		bean.setStrasse(adresseDTO.getStrasse());
		bean.setHausnummer(adresseDTO.getHausnummer());
		bean.setPlz(adresseDTO.getPlz());
		bean.setOrt(adresseDTO.getOrt());
		return bean;
	}
	
	private Adresse_ toAdresseBean(Adresse_DTO adresseDTO) {
		Adresse_ adresse = new Adresse_();
		adresse.setStrasse(adresseDTO.getStrasse());
		adresse.setHausnummer(adresseDTO.getHausnummer());
		adresse.setPlz(adresseDTO.getPlz());
		adresse.setOrt(adresseDTO.getOrt());
		return adresse;
	}
	
	/**
	 * Transform the local object representation to the DTO resource.
	 *
	 * @param bean the local object representation
	 * @return the REST DTO Resource
	 */
	public Adresse_DTO toDTO(Adresse_ bean) {
		Adresse_DTO adresseDTO = new Adresse_DTO();
		adresseDTO.setStrasse(bean.getStrasse());
		adresseDTO.setHausnummer(bean.getHausnummer());
		adresseDTO.setPlz(bean.getPlz());
		adresseDTO.setOrt(bean.getOrt());
		return adresseDTO;
	}
}
