package de.muenchen.kvr.buergerverwaltung.buerger.service.services.event;

import org.springframework.stereotype.Service;

import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Wohnung_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.services.event.Wohnung_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Wohnung_EventListener.
 */
@Service
public class Wohnung_EventServiceImpl implements Wohnung_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Wohnung_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Wohnung_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Wohnung_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Wohnung_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Wohnung_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Wohnung_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Wohnung_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Wohnung_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Wohnung_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Wohnung_ parent, Object linked) {
		// Add your logic here.
	}
}
