package de.muenchen.kvr.buergerverwaltung.buerger.service.services.event;

import org.springframework.stereotype.Service;

import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Sachbearbeiter_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.services.event.Sachbearbeiter_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Sachbearbeiter_EventListener.
 */
@Service
public class Sachbearbeiter_EventServiceImpl implements Sachbearbeiter_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Sachbearbeiter_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Sachbearbeiter_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Sachbearbeiter_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Sachbearbeiter_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Sachbearbeiter_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Sachbearbeiter_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Sachbearbeiter_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Sachbearbeiter_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Sachbearbeiter_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Sachbearbeiter_ parent, Object linked) {
		// Add your logic here.
	}
}
