--User Table
create table users (
oid bigint generated by default as identity, 
created_by varchar(255), 
created_date date, 
last_mod_by varchar(255), 
last_mod_date date, 
user_mandant varchar(20), 
user_enabled boolean, 
user_username varchar(255) not null, 
user_password varchar(255), 
user_email varchar(255), 
user_birthdate date, 
user_forname varchar(255), 
user_surname varchar(255), 
primary key (oid));

--Authority Table
create table authorities (
oid bigint generated by default as identity, 
created_by varchar(255), 
created_date date, 
last_mod_by varchar(255), 
last_mod_date date, 
auth_authority varchar(255), 
primary key (oid));

--Permission Table
create table permissions (
oid bigint generated by default as identity, 
created_by varchar(255), 
created_date date, 
last_mod_by varchar(255), 
last_mod_date date, 
perm_permission varchar(255), 
primary key (oid));

--users_authorities Table: Join Table between User and Authority
create table users_authorities (
user_oid bigint, 
authority_oid bigint, 
primary key (authority_oid, user_oid));

alter table users_authorities 
add constraint FK_users_authorities_TO_users 
foreign key (user_oid) 
references users;

alter table users_authorities 
add constraint FK_users_authorities_TO_authorities 
foreign key (authority_oid) 
references authorities;

--Authority-Permission Table: Join Table between Authority and Permission
create table authorities_permissions (
authority_oid bigint, 
permission_oid bigint, 
primary key (authority_oid, permission_oid));

alter table authorities_permissions 
add constraint FK_authorities_permissions_TO_authorities 
foreign key (authority_oid) 
references authorities;

alter table authorities_permissions 
add constraint FK_authorities_permissions_TO_permissions 
foreign key (permission_oid) 
references permissions;
