--**************************
--Tables
--**************************

--Buerger table
create table buerger (
oid bigint generated by default as identity,
mandant varchar(20),
vorname varchar(50) not null,
nachname varchar(50) not null,
geburtsdatum date not null,
augenfarbe varchar(30) not null,
alive boolean not null,
primary key (oid));

--Wohnung table
create table wohnung (
oid bigint generated by default as identity,
mandant varchar(20),
stock varchar(50) not null,
ausrichtung varchar(50) not null,
primary key (oid));

--Adresse table
create table adresse (
oid bigint generated by default as identity,
mandant varchar(20),
primary key (oid));

--AdresseExtern table
create table adresseextern (
oid bigint generated by default as identity,
mandant varchar(20),
strasse varchar(50) not null,
hausnummer bigint not null,
plz bigint not null,
ort varchar(50) not null,
primary key (oid));

--AdresseIntern table
create table adresseintern (
oid bigint generated by default as identity,
mandant varchar(20),
strassenschluessel bigint not null,
hausnummer bigint not null,
primary key (oid));

--Staatsangehoerigkeit table
create table staatsangehoerigkeit (
oid bigint generated by default as identity,
mandant varchar(20),
name varchar(30) not null,
primary key (oid));

--Pass table
create table pass (
oid bigint generated by default as identity,
mandant varchar(20),
passnummer bigint not null,
typ varchar(30) not null,
kode varchar(50) not null,
groesse bigint not null,
behoerde varchar(50) not null,
primary key (oid));

--Sachbearbeiter table
create table sachbearbeiter (
oid bigint generated by default as identity,
mandant varchar(20),
telefon bigint not null,
fax bigint not null,
funktion varchar(50) not null,
organisationseinheit varchar(50) not null,
primary key (oid));

 
--Buerger_Wohnungen Table
create table buerger_wohnungen (
buerger_oid bigint not null, 
wohnungen_oid bigint not null, 
primary key ( buerger_oid, wohnungen_oid));
 
--Buerger_Staatsangehoerigkeiten Table
create table buerger_staatsangehoerigkeiten (
buerger_oid bigint not null, 
staatsangehoerigkeiten_oid bigint not null, 
primary key ( buerger_oid, staatsangehoerigkeiten_oid));
 
--Buerger_Kinder Table
create table buerger_kinder (
buerger_oid bigint not null, 
kinder_oid bigint not null, 
primary key ( buerger_oid, kinder_oid));
 
--Buerger_Partner Table
create table buerger_partner (
buerger_oid bigint not null, 
partner_oid bigint not null, 
primary key ( buerger_oid, partner_oid));
 
--Buerger_Sachbearbeiter Table
create table buerger_sachbearbeiter (
buerger_oid bigint not null, 
sachbearbeiter_oid bigint not null, 
primary key ( buerger_oid, sachbearbeiter_oid));
 
--Buerger_Paesse Table
create table buerger_paesse (
buerger_oid bigint not null, 
paesse_oid bigint not null, 
primary key ( buerger_oid, paesse_oid));
 
--Wohnung_Adresse Table
create table wohnung_adresse (
wohnung_oid bigint not null, 
adresse_oid bigint not null, 
primary key ( wohnung_oid, adresse_oid));
 
--Adresse_InterneAdresse Table
create table adresse_interneAdresse (
adresse_oid bigint not null, 
interneAdresse_oid bigint not null, 
primary key ( adresse_oid, interneAdresse_oid));
 
--Adresse_ExterneAdresse Table
create table adresse_externeAdresse (
adresse_oid bigint not null, 
externeAdresse_oid bigint not null, 
primary key ( adresse_oid, externeAdresse_oid));
alter table buerger_wohnungen 
add constraint FK_buerger_wohnungen_TO_wohnungen 
foreign key (wohnungen_oid) 
references wohnung;
 
alter table buerger_wohnungen 
add constraint FK_buerger_wohnungen_TO_buerger 
foreign key (buerger_oid) 
references buerger;
 
alter table buerger_staatsangehoerigkeiten 
add constraint FK_buerger_staatsangehoerigkeiten_TO_staatsangehoerigkeiten 
foreign key (staatsangehoerigkeiten_oid) 
references staatsangehoerigkeit;
 
alter table buerger_staatsangehoerigkeiten 
add constraint FK_buerger_staatsangehoerigkeiten_TO_buerger 
foreign key (buerger_oid) 
references buerger;
 
alter table buerger_kinder 
add constraint FK_buerger_kinder_TO_kinder 
foreign key (kinder_oid) 
references buerger;
 
alter table buerger_kinder 
add constraint FK_buerger_kinder_TO_buerger 
foreign key (buerger_oid) 
references buerger;
 
alter table buerger_partner 
add constraint FK_buerger_partner_TO_partner 
foreign key (partner_oid) 
references buerger;
 
alter table buerger_partner 
add constraint FK_buerger_partner_TO_buerger 
foreign key (buerger_oid) 
references buerger;
 
alter table buerger_sachbearbeiter 
add constraint FK_buerger_sachbearbeiter_TO_sachbearbeiter 
foreign key (sachbearbeiter_oid) 
references sachbearbeiter;
 
alter table buerger_sachbearbeiter 
add constraint FK_buerger_sachbearbeiter_TO_buerger 
foreign key (buerger_oid) 
references buerger;
 
alter table buerger_paesse 
add constraint FK_buerger_paesse_TO_paesse 
foreign key (paesse_oid) 
references pass;
 
alter table buerger_paesse 
add constraint FK_buerger_paesse_TO_buerger 
foreign key (buerger_oid) 
references buerger;
 
 
alter table wohnung_adresse 
add constraint FK_wohnung_adresse_TO_adresse 
foreign key (adresse_oid) 
references adresse;
 
alter table wohnung_adresse 
add constraint FK_wohnung_adresse_TO_wohnung 
foreign key (wohnung_oid) 
references wohnung;
 
 
alter table adresse_interneAdresse 
add constraint FK_adresse_interneAdresse_TO_interneAdresse 
foreign key (interneAdresse_oid) 
references adresseIntern;
 
alter table adresse_interneAdresse 
add constraint FK_adresse_interneAdresse_TO_adresse 
foreign key (adresse_oid) 
references adresse;
 
alter table adresse_externeAdresse 
add constraint FK_adresse_externeAdresse_TO_externeAdresse 
foreign key (externeAdresse_oid) 
references adresseExtern;
 
alter table adresse_externeAdresse 
add constraint FK_adresse_externeAdresse_TO_adresse 
foreign key (adresse_oid) 
references adresse;
 
 
 
 
 
 
 
