--**************************
--Tables
--**************************


--Accounts table
create table accounts (
oid varchar(32) generated by default as identity,
created_by varchar(255),
created_date date,
last_mod_by varchar(255),
last_mod_date date,
primary key (oid));

--Adresse_Externe Table
create table adresse_externe (
oid varchar(32) generated by default as identity,
adr_hausnummer varchar(70), 
adr_plz integer, 
adr_stadt varchar(20), 
adr_str varchar(70), 
andant VARCHAR(20), 
primary key (oid));

--Adresse_interne Table
create table adresse_interne (
oid varchar(32) generated by default as identity, 
adr_hausnummer varchar(70), 
adr_strasse varchar(70), 
mandant VARCHAR(20), 
primary key (oid));

--Adresse_reference Table
create table adresse_reference (
oid varchar(32) generated by default as identity, 
mandant varchar(20), 
adr_externe_oid varchar(32), 
adr_interne_oid VARCHAR(20), 
primary key (oid));

--Authority Table
create table authoritys (
oid varchar(32) generated by default as identity, 
created_by varchar(255), 
created_date date, 
last_mod_by varchar(255), 
last_mod_date date, 
auth_authority varchar(255), 
primary key (oid));

--Authority-Permission Table
create table authoritys_permissions (
authority_oid varchar(32), 
permission_oid varchar(32), 
primary key (authority_oid, permission_oid));

--Buerger Table
create table buerger (
oid varchar(32) generated by default as identity, 
buer_geburtsdatum date, 
buer_nachname varchar(70) not null, 
buer_vorname varchar(70), 
mandant varchar(20), 
primary key (oid));

--Buerger_Kinder Table
create table buerger_kinder (
buerger varchar(32) not null, 
kinder varchar(32) not null, 
primary key (buerger, kinder));

--Buerger_Partner Table
create table buerger_partner (
buerger varchar(32) not null, 
partner varchar(32) not null, 
primary key (buerger, partner));

--Buerger_Pass Table
create table buerger_pass (
buerger varchar(32) not null, 
pass varchar(32) not null, 
primary key (buerger, pass));

--Buerger_Sachbearbeiter Table
create table buerger_sachbearbeiter (
buerger varchar(32) not null, 
sachbearbeiter varchar(32) not null, 
primary key (buerger, sachbearbeiter));

--buerger_staatsangehoerigkeit Table
create table buerger_staatsangehoerigkeit_references (
buerger varchar(32) not null, 
staatsangehoerigkeit_references varchar(32) not null, 
primary key (buerger, staatsangehoerigkeit_references));


--Buerger_Wohnung Table
create table buerger_wohnungen (
buerger varchar(32) not null, 
wohnungen varchar(32) not null, 
primary key (buerger, wohnungen));


--Company_base_infos Table
create table company_base_infos (
oid varchar(32) generated by default as identity, 
created_by varchar(255), 
created_date date, 
last_mod_by varchar(255), 
last_mod_date date, 
comp_adress varchar(255), 
comp_name varchar(255), 
primary key (oid));

--company_base_infos_accounts Table
create table company_base_infos_accounts (
company_base_infos varchar(32) not null, 
accounts varchar(32) not null, 
primary key (company_base_infos, accounts));

--Pass Table
create table pass (
oid varchar(32) generated by default as identity, 
pass_typ varchar(10), 
pass_augenfarbe varchar(70), 
pass_austellungsdatum date, 
pass_behoerde varchar(70), 
pass_groesse varchar(20), 
pass_gueltig_bis date, 
pass_kode varchar(10), 
pass_passnummer varchar(70), 
mandant varchar(20), 
staatsangehoerigkeit_reference varchar(32), 
primary key (oid));

--Permissions Table
create table permissions (
oid varchar(32) generated by default as identity, 
created_by varchar(255), 
created_date date, 
last_mod_by varchar(255), 
last_mod_date date, 
perm_permission varchar(255), 
primary key (oid));

--Revinfo Table
create table revinfo (
rev integer generated by default as identity, 
revtstmp varchar(32), 
primary key (rev));

--staatsangehoerigkeit_reference Table
create table staatsangehoerigkeit_reference (
oid varchar(32) generated by default as identity,  
ref_oid varchar(100) not null, 
mandant varchar(20), 
primary key (oid));

--User Table
create table users (
oid varchar(32) generated by default as identity, 
user_birthdate date, 
created_by varchar(255), 
created_date date, 
user_email varchar(255), 
user_enabled boolean, 
user_forname varchar(255), 
last_mod_by varchar(255), 
last_mod_date date, 
user_password varchar(255), 
user_surname varchar(255), 
user_username varchar(255) not null, 
mandant varchar(20), 
primary key (oid));


--users_accounts Table
create table users_accounts (
users varchar(32) not null, 
accounts varchar(32) not null, 
primary key (users, accounts));


--users_authoritys Table
create table users_authoritys (
user_oid varchar(32), 
authority_oid varchar(32), 
primary key (authority_oid, user_oid));


--Wohnung Table
create table wohnungen (
oid varchar(32) generated by default as identity,  
wohn_ausrichtung varchar(20), 
wohn_stock varchar(255), 
mandant varchar(20), 
adresse_oid varchar(32), 
primary key (oid));

--Sachbearbeiter Table
create table sachbearbeiter (
oid varchar(32) generated by default as identity, 
sach_funktion varchar(50), 
sach_fax varchar(50),
sach_telephone varchar(50), 
sach_organisationseinheit varchar(50),
user_oid varchar(32), 
mandant varchar(20), 
primary key (oid));

--Sachbearbeiter_Buerger Table
create table sachbearbeiter_buerger (
sachbearbeiter varchar(32) not null, 
buerger varchar(32) not null, 
primary key ( sachbearbeiter,buerger));

--**************************
--Foreign Keys
--**************************
alter table adresse_reference
add constraint FK_adresse_reference_TO_adresse_externe 
foreign key (adr_externe_oid) 
references adresse_externe;

alter table adresse_reference 
add constraint FK_adresse_reference_TO_adresse_interne 
foreign key (adr_interne_oid) 
references adresse_interne;

alter table authoritys_permissions 
add constraint FK_authoritys_permissions_TO_authoritys 
foreign key (authority_oid) 
references authoritys;

alter table authoritys_permissions 
add constraint FK_authoritys_permissions_TO_permissions 
foreign key (permission_oid) 
references permissions;

alter table buerger_kinder 
add constraint FK_buerger_kinder_TO_kinder 
foreign key (kinder) 
references buerger;

alter table buerger_kinder 
add constraint FK_buerger_kinder_TO_buerger 
foreign key (buerger) 
references buerger;

alter table buerger_pass 
add constraint FK_buerger_pass_TO_pass 
foreign key (pass) 
references pass;

alter table buerger_pass 
add constraint FK_buerger_pass_TO_buerger 
foreign key (buerger) 
references buerger;

alter table buerger_sachbearbeiter 
add constraint FK_buerger_sachbearbeiter_TO_sachbearbeiter 
foreign key (sachbearbeiter) 
references sachbearbeiter;

alter table buerger_sachbearbeiter 
add constraint FK_buerger_sachbearbeiter_TO_buerger 
foreign key (buerger) 
references buerger;

alter table buerger_staatsangehoerigkeit_references 
add constraint FK_buerger_staatsangehoerigkeit_references_TO_staatsangehoerigkeit_reference 
foreign key (staatsangehoerigkeit_references) 
references staatsangehoerigkeit_reference;

alter table buerger_staatsangehoerigkeit_references 
add constraint FK_buerger_staatsangehoerigkeit_references_TO_buerger 
foreign key (buerger) 
references buerger;

alter table buerger_wohnungen 
add constraint FK_buerger_wohnungen_TO_wohnungen 
foreign key (wohnungen) 
references wohnungen;

alter table buerger_wohnungen 
add constraint FK_buerger_wohnungen_TO_buerger 
foreign key (buerger) 
references buerger;

alter table sachbearbeiter_buerger 
add constraint FK_sachbearbeiter_buerger_TO_sachbearbeiter 
foreign key (sachbearbeiter) 
references sachbearbeiter;

alter table sachbearbeiter_buerger 
add constraint FK_sachbearbeiter_buerger_TO_buerger 
foreign key (buerger) 
references buerger;

alter table company_base_infos_accounts 
add constraint FK_company_base_infos_accounts_TO_accounts 
foreign key (accounts) 
references accounts;

alter table company_base_infos_accounts 
add constraint FK_company_base_infos_accounts_TO_company_base_infos 
foreign key (company_base_infos) 
references company_base_infos;

alter table pass 
add constraint FK_pass_TO_staatsangehoerigkeit_reference 
foreign key (staatsangehoerigkeit_reference) 
references staatsangehoerigkeit_reference;

alter table users_accounts 
add constraint FK_users_accounts_TO_accounts 
foreign key (accounts) 
references accounts;

alter table users_accounts 
add constraint FK_users_accounts_TO_users 
foreign key (users) 
references users;

alter table users_authoritys 
add constraint FK_users_authoritys_TO_users 
foreign key (user_oid) 
references users;

alter table users_authoritys 
add constraint FK_users_authoritys_TO_authoritys 
foreign key (authority_oid) 
references authoritys;

alter table wohnungen 
add constraint FK_wohnungen_TO_adresse_reference 
foreign key (adresse_oid) 
references adresse_reference;
