package de.muenchen.kvr.buergerverwaltung.buerger.client.local;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
import java.util.stream.Stream;

import javax.validation.constraints.NotNull;
import org.springframework.hateoas.ResourceSupport;
/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class AdresseIntern_ {
	
	@NotNull
	private long strassenSchluessel;
	
	@NotNull
	private long hausnummer;
	
	public AdresseIntern_(){}
	
	/**
     * Create a new AdresseIntern_ with the  strassenSchluessel, hausnummer.
     *
     * @param strassenSchluessel the strassenSchluessel of the AdresseIntern_.
     * @param hausnummer the hausnummer of the AdresseIntern_.
     */
    public AdresseIntern_( long strassenSchluessel, long hausnummer) {
        this.setStrassenSchluessel(strassenSchluessel);
        this.setHausnummer(hausnummer);
    }
	
	// Getters and Setters
	public long getStrassenSchluessel(){
		return strassenSchluessel;
	}
	
	public void setStrassenSchluessel(long strassenSchluessel){
		this.strassenSchluessel = strassenSchluessel;
	}
	
	public long getHausnummer(){
		return hausnummer;
	}
	
	public void setHausnummer(long hausnummer){
		this.hausnummer = hausnummer;
	}
	
	 /**
      * A simple Enum for all the Fields of this AdresseIntern_.
      * <p>
      *     You can use {@link Field#name()} for the String.
      * </p>
      */
	public enum Field {
        strassenSchluessel, hausnummer;

        private final boolean field;

        Field() {
			this(true);
		}

		Field(boolean field) {
			this.field = field;
		}

		public boolean isField() {
			return field;
		}

		public static String[] getProperties() {
			return Stream.of(values()).filter(Field::isField).map(Field::name).toArray(String[]::new);
		}
	}
	
	 /**
	  * A simple Enum for all the Relations ({@link AdresseIntern_#getLink(String)} of the AdresseIntern_.
	  * <p>
	  *     You can use {@link Rel#name()} for the String.
	  * </p>
	  */
	 public enum Rel {
	 	;
    }
	
	@Override
	public String toString(){
		String s = "";
		s += "long strassenSchluessel: " + this.getStrassenSchluessel();
		s += "long hausnummer: " + this.getHausnummer();
		return s;
	}
}
