package de.muenchen.kvr.buergerverwaltung.buerger.client.local;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
import java.util.stream.Stream;

import javax.validation.constraints.NotNull;
import org.springframework.hateoas.ResourceSupport;
/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Sachbearbeiter_ extends ResourceSupport {
	
	@NotNull
	private long telefon;
	
	@NotNull
	private long fax;
	
	@NotNull
	private String funktion;
	
	@NotNull
	private String organisationseinheit;
	
	public Sachbearbeiter_(){}
	
	/**
     * Create a new Sachbearbeiter_ with the  telefon, fax, funktion, organisationseinheit.
     *
     * @param telefon the telefon of the Sachbearbeiter_.
     * @param fax the fax of the Sachbearbeiter_.
     * @param funktion the funktion of the Sachbearbeiter_.
     * @param organisationseinheit the organisationseinheit of the Sachbearbeiter_.
     */
    public Sachbearbeiter_( long telefon, long fax, String funktion, String organisationseinheit) {
        this.setTelefon(telefon);
        this.setFax(fax);
        this.setFunktion(funktion);
        this.setOrganisationseinheit(organisationseinheit);
    }
	
	// Getters and Setters
	public long getTelefon(){
		return telefon;
	}
	
	public void setTelefon(long telefon){
		this.telefon = telefon;
	}
	
	public long getFax(){
		return fax;
	}
	
	public void setFax(long fax){
		this.fax = fax;
	}
	
	public String getFunktion(){
		return funktion;
	}
	
	public void setFunktion(String funktion){
		this.funktion = funktion;
	}
	
	public String getOrganisationseinheit(){
		return organisationseinheit;
	}
	
	public void setOrganisationseinheit(String organisationseinheit){
		this.organisationseinheit = organisationseinheit;
	}
	
	 /**
      * A simple Enum for all the Fields of this Sachbearbeiter_.
      * <p>
      *     You can use {@link Field#name()} for the String.
      * </p>
      */
	public enum Field {
        telefon, fax, funktion, organisationseinheit;

        private final boolean field;

        Field() {
			this(true);
		}

		Field(boolean field) {
			this.field = field;
		}

		public boolean isField() {
			return field;
		}

		public static String[] getProperties() {
			return Stream.of(values()).filter(Field::isField).map(Field::name).toArray(String[]::new);
		}
	}
	
	 /**
	  * A simple Enum for all the Relations ({@link Sachbearbeiter_#getLink(String)} of the Sachbearbeiter_.
	  * <p>
	  *     You can use {@link Rel#name()} for the String.
	  * </p>
	  */
	 public enum Rel {
	 	;
    }
	
	@Override
	public String toString(){
		String s = "";
		s += "long telefon: " + this.getTelefon();
		s += "long fax: " + this.getFax();
		s += "String funktion: " + this.getFunktion();
		s += "String organisationseinheit: " + this.getOrganisationseinheit();
		return s;
	}
}
