package de.muenchen.kvr.buergerverwaltung.buerger.client.local;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
import java.util.stream.Stream;

import javax.validation.constraints.NotNull;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Adresse_;
import org.springframework.hateoas.ResourceSupport;
/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Wohnung_ extends ResourceSupport {
	
	@NotNull
	private String stock;
	
	private String ausrichtung;
	
	private Adresse_ adresse;
	
	public Wohnung_(){}
	
	/**
     * Create a new Wohnung_ with the  stock, ausrichtung.
     *
     * @param stock the stock of the Wohnung_.
     * @param ausrichtung the ausrichtung of the Wohnung_.
     */
    public Wohnung_( String stock, String ausrichtung) {
        this.setStock(stock);
        this.setAusrichtung(ausrichtung);
    }
	
	// Getters and Setters
	public String getStock(){
		return stock;
	}
	
	public void setStock(String stock){
		this.stock = stock;
	}
	
	public String getAusrichtung(){
		return ausrichtung;
	}
	
	public void setAusrichtung(String ausrichtung){
		this.ausrichtung = ausrichtung;
	}
	
	public Adresse_ getAdresse(){
		return adresse;
	}
	public void setAdresse(Adresse_ value){
		this.adresse = value;
	}
	
	 /**
      * A simple Enum for all the Fields of this Wohnung_.
      * <p>
      *     You can use {@link Field#name()} for the String.
      * </p>
      */
	public enum Field {
        stock, ausrichtung;

        private final boolean field;

        Field() {
			this(true);
		}

		Field(boolean field) {
			this.field = field;
		}

		public boolean isField() {
			return field;
		}

		public static String[] getProperties() {
			return Stream.of(values()).filter(Field::isField).map(Field::name).toArray(String[]::new);
		}
	}
	
	 /**
	  * A simple Enum for all the Relations ({@link Wohnung_#getLink(String)} of the Wohnung_.
	  * <p>
	  *     You can use {@link Rel#name()} for the String.
	  * </p>
	  */
	 public enum Rel {
	 	;
    }
	
	@Override
	public String toString(){
		String s = "";
		s += "String stock: " + this.getStock();
		s += "String ausrichtung: " + this.getAusrichtung();
		return s;
	}
}
