package de.muenchen.kvr.buergerverwaltung.buergerverwaltung;

import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.embedded.FilterRegistrationBean;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.filter.HiddenHttpMethodFilter;

import com.vaadin.spring.annotation.UIScope;

import de.muenchen.eventbus.EventBus;		

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */		
@SpringBootApplication
@EnableEurekaClient
@Configuration
@ComponentScan(basePackages = {"de.muenchen.kvr.buergerverwaltung","de.muenchen.kvr.buergerverwaltung.guilib","de.muenchen.kvr.buergerverwaltung.client",
	"de.muenchen.vaadin.demo.apilib","de.muenchen.vaadin.guilib","de.muenchen.vaadin.demo.i18nservice"})
//Exclude SecAutoConfig because OAuth needs to be manually configured
@EnableAutoConfiguration(exclude = {
org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration.class})
public class GuiApplication {
    
    public static void main(String[] args) throws Exception {
        new SpringApplicationBuilder(GuiApplication.class).run(args);
    }

    @Bean
    public FilterRegistrationBean hiddenHttpMethodFilter() {

        HiddenHttpMethodFilter hiddenHttpMethodFilter = new HiddenHttpMethodFilter();
        FilterRegistrationBean registrationBean = new FilterRegistrationBean();
        registrationBean.setFilter(hiddenHttpMethodFilter);
        return registrationBean;
    }

    @Bean
    @UIScope
    public EventBus eventbus(){
        return new EventBus();
    }
    
}
