package de.muenchen.vaadin.guilib.security.components.buttons.listener;

import de.muenchen.vaadin.demo.apilib.local.Authority;
import de.muenchen.vaadin.guilib.components.actions.EntitySingleActions;

import java.util.function.Supplier;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Authority_SingleActions extends EntitySingleActions<Authority> {
    public Authority_SingleActions(Supplier<Authority> authoritySupplier) {
        super(authoritySupplier, Authority.class);
    }
}
