package de.muenchen.vaadin.guilib.security.components.buttons.listener;

import de.muenchen.vaadin.demo.apilib.local.Authority_;
import de.muenchen.vaadin.guilib.components.actions.EntityListActions;

import java.util.List;
import java.util.function.Supplier;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Authority_ListActions extends EntityListActions<Authority_> {
    public Authority_ListActions(Supplier<List<Authority_>> authoritySupplier) {
        super(authoritySupplier, Authority_.class);
    }
}
