package de.muenchen.vaadin.guilib.security.components.buttons.listener;

import de.muenchen.eventbus.events.Association;
import de.muenchen.vaadin.demo.apilib.local.Authority_;
import de.muenchen.vaadin.guilib.components.actions.EntityAssociationActions;

import java.util.function.Supplier;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Authority_AssociationActions extends EntityAssociationActions<Authority_> {
    public Authority_AssociationActions(Supplier<Association<?>> associationSupplier) {
        super(associationSupplier, Authority_.class);
    }
}
