package de.muenchen.vaadin.guilib.security.components.buttons.listener;

import de.muenchen.vaadin.demo.apilib.local.Permission;
import de.muenchen.vaadin.guilib.components.actions.EntityActions;

import java.util.function.Supplier;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_Actions extends EntityActions {

    public Permission_Actions(Supplier<String> filterSupplier) {
        super(filterSupplier, Permission.class);
    }
}
