package de.muenchen.vaadin.guilib.security.components.buttons.listener;

import de.muenchen.vaadin.demo.apilib.local.Permission;
import de.muenchen.vaadin.guilib.components.actions.EntityListActions;

import java.util.List;
import java.util.function.Supplier;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_ListActions extends EntityListActions<Permission> {
    public Permission_ListActions(Supplier<List<Permission>> permissionSupplier) {
        super(permissionSupplier, Permission.class);
    }
}
