package de.muenchen.vaadin.guilib.security.components.buttons.listener;

import de.muenchen.vaadin.demo.apilib.local.User;
import de.muenchen.vaadin.guilib.components.actions.EntitySingleActions;

import java.util.function.Supplier;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class User_SingleActions extends EntitySingleActions<User> {
    public User_SingleActions(Supplier<User> userSupplier) {
        super(userSupplier, User.class);
    }
}
