	-- This file is for H2

	--**************************
	--Tables
	--**************************
	
	
	create table Buerger (
	oid bigint generated by default as identity,
	vorname varchar(255) not null, 
	nachname varchar(255) not null, 
	geburtstag date not null, 
	augenfarbe varchar(255) not null, 
	telefonnummer bigint not null, 
	email varchar(255) not null, 
	lebendig boolean not null, 
	primary key (oid));
	
	
	
	
	create table Adresse (
	oid bigint generated by default as identity,
	interneadresse_strassenschluessel bigint not null, 
	interneadresse_hausnummer bigint not null, 
	externeadresse_strasse varchar(255) not null, 
	externeadresse_hausnummer bigint not null, 
	externeadresse_plz bigint not null, 
	externeadresse_ort varchar(255) not null, 
	primary key (oid));
	
	
	
	
	
	
	
	
	create table Pass (
	oid bigint generated by default as identity,
	passnummer bigint not null, 
	typ varchar(255) not null, 
	kode varchar(255) not null, 
	groesse bigint not null, 
	behoerde varchar(255) not null, 
	primary key (oid));
	
	
	
	
	create table Sachbearbeiter (
	oid bigint generated by default as identity,
	telefon bigint not null, 
	fax bigint not null, 
	funktion varchar(255) not null, 
	organisationseinheit varchar(255) not null, 
	primary key (oid));
	
	
	
	
	create table Wohnung (
	oid bigint generated by default as identity,
	stock varchar(255) not null, 
	ausrichtung varchar(255), 
	primary key (oid));
	
	
	
	--Buerger_Kinder Relation Table
	create table Buerger_Kinder (
	buerger_oid bigint not null, 
	kinder_oid bigint not null, 
	order_index bigint,
	primary key ( buerger_oid, kinder_oid));
	
	alter table Buerger_Kinder 
	add constraint FK_buerger_kinder_TO_kinder 
	foreign key (kinder_oid) 
	references Buerger(oid);
	
	alter table Buerger_Kinder 
	add constraint FK_buerger_kinder_TO_buerger 
	foreign key (buerger_oid) 
	references Buerger(oid);
	
	
	--Buerger_Partner Relation Table
	create table Buerger_Partner (
	buerger_oid bigint not null unique, 
	partner_oid bigint not null unique, 
	primary key ( buerger_oid, partner_oid));
	
	alter table Buerger_Partner 
	add constraint FK_buerger_partner_TO_partner 
	foreign key (partner_oid) 
	references Buerger(oid);
	
	alter table Buerger_Partner 
	add constraint FK_buerger_partner_TO_buerger 
	foreign key (buerger_oid) 
	references Buerger(oid);
	
	
	--Buerger_Wohnungen Relation Table
	create table Buerger_Wohnungen (
	buerger_oid bigint not null unique, 
	wohnungen_oid bigint not null, 
	primary key ( buerger_oid, wohnungen_oid));
	
	alter table Buerger_Wohnungen 
	add constraint FK_buerger_wohnungen_TO_wohnungen 
	foreign key (wohnungen_oid) 
	references Wohnung(oid);
	
	alter table Buerger_Wohnungen 
	add constraint FK_buerger_wohnungen_TO_buerger 
	foreign key (buerger_oid) 
	references Buerger(oid);
	
	
	--Buerger_Sachbearbeiter Relation Table
	create table Buerger_Sachbearbeiter (
	buerger_oid bigint not null, 
	sachbearbeiter_oid bigint not null, 
	order_index bigint,
	primary key ( buerger_oid, sachbearbeiter_oid));
	
	alter table Buerger_Sachbearbeiter 
	add constraint FK_buerger_sachbearbeiter_TO_sachbearbeiter 
	foreign key (sachbearbeiter_oid) 
	references Sachbearbeiter(oid);
	
	alter table Buerger_Sachbearbeiter 
	add constraint FK_buerger_sachbearbeiter_TO_buerger 
	foreign key (buerger_oid) 
	references Buerger(oid);
	
	
	--Buerger_Pass Relation Table
	create table Buerger_Pass (
	buerger_oid bigint not null unique, 
	pass_oid bigint not null, 
	primary key ( buerger_oid, pass_oid));
	
	alter table Buerger_Pass 
	add constraint FK_buerger_pass_TO_pass 
	foreign key (pass_oid) 
	references Pass(oid);
	
	alter table Buerger_Pass 
	add constraint FK_buerger_pass_TO_buerger 
	foreign key (buerger_oid) 
	references Buerger(oid);
	
	
	
	
	--Wohnung_Adresse Relation Table
	create table Wohnung_Adresse (
	wohnung_oid bigint not null, 
	adresse_oid bigint not null unique, 
	order_index bigint,
	primary key ( wohnung_oid, adresse_oid));
	
	alter table Wohnung_Adresse 
	add constraint FK_wohnung_adresse_TO_adresse 
	foreign key (adresse_oid) 
	references Adresse(oid);
	
	alter table Wohnung_Adresse 
	add constraint FK_wohnung_adresse_TO_wohnung 
	foreign key (wohnung_oid) 
	references Wohnung(oid);
	
	
	
