package de.muenchen.vaadin.guilib.security.controller;

import com.vaadin.spring.annotation.SpringComponent;
import com.vaadin.spring.annotation.UIScope;

import de.muenchen.eventbus.EventBus;
import de.muenchen.eventbus.events.Association;
import de.muenchen.eventbus.selector.entity.RequestEntityKey;
import de.muenchen.eventbus.selector.entity.RequestEvent;
import de.muenchen.eventbus.selector.entity.ResponseEntityKey;

import de.muenchen.vaadin.demo.apilib.local.Authority;
import de.muenchen.vaadin.demo.apilib.local.Permission;
import de.muenchen.vaadin.guilib.security.services.Authority_Service;
import de.muenchen.vaadin.guilib.security.services.Permission_Service;
import de.muenchen.vaadin.guilib.security.services.model.Authority_Datastore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.ResourceSupport;
import org.springframework.hateoas.Link;
import reactor.bus.Event;

import javax.annotation.PostConstruct;
import java.io.Serializable;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import de.muenchen.vaadin.guilib.BaseUI;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
@SpringComponent
@UIScope
public class Authority_ViewController implements Serializable{

	private static final long serialVersionUID = 1L;
	
	/**
	 * Logger
	 */
	private static final Logger LOG = LoggerFactory.getLogger(Authority_ViewController.class);
	
	/**
	 * Die Authority_Service Klasse
	 */
	@Autowired
	Authority_Service authorityService;
	
	/**
	 * Die Permission_Service Klasse
	 */
	@Autowired
	Permission_Service permissionService;
	
	private final Authority_Datastore model = new Authority_Datastore();
	

	@PostConstruct
	private void init() {
		initEventhandlers();
	}
	
	private EventBus getEventbus() {
        return BaseUI.getCurrentEventBus();
    }
	
	public Authority_Datastore getModel() {
		return model;
	}

	////////////////////////
	// Service Operations //
	////////////////////////

	/**
	 * Speichert ein {@link Authority} Objekt in der Datenbank.
	 *
	 * @param authority Authority_ der gespeichert werden soll
	 */
	public Authority save(Authority authority) {
		return authorityService.create(authority);
	}

	/**
	 * Zerstört die Verbindung zwischen einem Authority_ und seinem permissions
	 *
	 * @param event
	 */
	private void releasePermissions(Permission event) {
		Link link = getModel().getSelectedAuthority().get().getLink(Authority.Rel.permissions.name());
		List<Link> permissions = permissionService.findAll(link)
				.stream()
				.map(Permission::getId)
				.filter(id -> !id.equals(event.getId()))
				.collect(Collectors.toList());

		authorityService.setRelations(link, permissions);
	}
	
	
	/**
	 * Speichert eine beziehung als permissions zu einem {@link Permission} Objekt in der Datenbank.
	 *
	 * @param permissionsEntity Permissions
	 * @return Permission_
	 */
	public void addAuthorityPermissions(Permission permissionsEntity) {
		Link link = getModel().getSelectedAuthority().get().getLink(Authority.Rel.permissions.name());
		List<Link> permissionslist = Stream.concat(
				permissionService.findAll(link)
						.stream()
						.map(Permission::getId),
				Stream.of(permissionsEntity.getId()))
	
				.collect(Collectors.toList());
	
		authorityService.setRelations(link, permissionslist);
	}
	
	public List<Permission> queryPermissions(Authority entity) {
		return permissionService.findAll(entity.getLink(Authority.Rel.permissions.name())).stream().collect(Collectors.toList());
	}
	/**
	 * Speichert die Änderungen an einem {@link Authority} Objekt in der Datenbank.
	 *
	 * @param entity Authority_
	 * @return Authority_
	 */
	public Authority updateAuthority(Authority entity) {
		return authorityService.update(entity);
	}

	/**
	 * Löscht ein {@link Authority} Objekt.
	 *
	 * @param entity Authority_
	 */
	public void deleteAuthority(Authority entity) {
		authorityService.delete(entity.getId());
	}

	public List<Authority> queryAuthority() {
		return authorityService.findAll().stream().collect(Collectors.toList());
	}

	public List<Authority> queryAuthority(String query) {
		return authorityService.queryAuthority(query);
	}
	
	/////////////////////
	// Event Steuerung //
	/////////////////////

	/**
	 * Register all event handlers on the RequestEntityKey.
	 */
	private void initEventhandlers() {
		getEventbus().on(getRequestKey(RequestEvent.CREATE).toSelector(), this::create);
		getEventbus().on(getRequestKey(RequestEvent.DELETE).toSelector(), this::delete);
		getEventbus().on(getRequestKey(RequestEvent.UPDATE).toSelector(), this::update);
		getEventbus().on(getRequestKey(RequestEvent.ADD_ASSOCIATION).toSelector(), this::addAssociation);
		getEventbus().on(getRequestKey(RequestEvent.REMOVE_ASSOCIATION).toSelector(), this::removeAssociation);
		getEventbus().on(getRequestKey(RequestEvent.READ_LIST).toSelector(), this::readList);
		getEventbus().on(getRequestKey(RequestEvent.READ_SELECTED).toSelector(), this::readSelected);
	}

	/**
	 * Remove the specified Association from the specified Relation and update the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Association} as {@link Event#getData()}.
	 */
	void removeAssociation(Event<?> event) {
		final Object data = event.getData();
		if (data == null)
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Association.class)
			throw new IllegalArgumentException("The event must be of " + Association.class);

		final Association<?> association = (Association<?>) event.getData();
		final Authority.Rel rel = Authority.Rel.valueOf(association.getRel());
		
		if (Authority.Rel.permissions == rel) {
			Permission permissions = (Permission) association.getAssociation();
			releasePermissions(permissions);
			getModel().getSelectedAuthorityPermissions().removeItem(permissions);
		}
		notifyComponents();
	}

	/**
	 * Add the specified Association to the specified Relation and update the DataStore.
	 * <p>	 
	 * If the {@link Association#getAssociation()} has no {@link ResourceSupport#getId()} the Resouce will be created
	 * on the DataStore first.
	 * </p>
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Association} as {@link Event#getData()}.
	 */
	private void addAssociation(Event<?> event) {
		final Object data = event.getData();
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Association.class)
			throw new IllegalArgumentException("The event must be of " + Association.class);

		final Association<?> association = (Association<?>) event.getData();

		final Authority.Rel rel = Authority.Rel.valueOf(association.getRel());
		if (Authority.Rel.permissions == rel) {
			Permission permissions = (Permission) association.getAssociation();
			// If Permissions has no ID he has to be created in the backend
			if (permissions.getId() == null) {
				permissions = permissionService.create(permissions);
			}
			addAuthorityPermissions(permissions);
			getModel().getSelectedAuthorityPermissions().addBean(permissions);
		}
		refreshModelAssociations();
		notifyComponents();
	}

	/**	
	 * Create a new Buerger on the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Authority} as {@link Event#getData()}.
	 */
	private void create(Event<?> event) {
		final Object data = event.getData();
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Authority.class)
			throw new IllegalArgumentException("The event must be of " + Authority.class);
		final Authority authority = (Authority) event.getData();
		final Authority fromREST = authorityService.create(authority);
		getModel().getAuthoritys().addBean(fromREST);
		notifyComponents();
	}


	/**
	 * Delete the Authority_ on the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Authority} as {@link Event#getData()}.
	 */
	private void delete(Event<?> event) {
		final Object data = event.getData();
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Authority.class)
			throw new IllegalArgumentException("The event must be of " + Authority.class);
		final Authority authority = (Authority) event.getData();
		if (authority.getId() == null)
			throw new IllegalArgumentException("The Authority_ must have an ID.");
		authorityService.delete(authority.getId());
		getModel().getSelectedAuthority().ifPresent(selectedAuthority -> {
			if (selectedAuthority.equals(authority)) {
				getModel().setSelectedAuthority(null);
				// reset all selected relations
				getModel().getSelectedAuthorityPermissions().removeAllItems();
			}
		});
		getModel().getAuthoritys().removeItem(authority);
		notifyComponents();
	}

	/**
	 * Update the Authority_ on the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Authority} as {@link Event#getData()}.
	 */
	private void update(Event<?> event) {
		final Object data = event.getData();	 
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Authority.class)
			throw new IllegalArgumentException("The event must be of " + Authority.class);
		final Authority authority = (Authority) event.getData();
		if (authority.getId() == null)
			throw new IllegalArgumentException("The Authority_ must have an ID.");
		final Authority fromREST = authorityService.update(authority);
		refreshModelSelected();
		getModel().getAuthoritys().addBean(fromREST);
		notifyComponents();
	}

	/**
	 * Refresh the {@link Authority_Datastore#authoritys} list from the DataStore.
	 * <p/>	
	 * <p>
	 * This method also filters by the query (ifPresent).
	 * </p>
	 */
	private void refreshModelList() {
		final Optional<String> query = getModel().getQuery();
		if (query.isPresent()) {
			getModel().getAuthoritys().removeAllItems();
			getModel().getAuthoritys().addAll(queryAuthority(query.get()));
		} else {
			getModel().getAuthoritys().removeAllItems();
			getModel().getAuthoritys().addAll(queryAuthority());
		}
	}

	/**
	 * Refresh *all* the associations of the selected Authority_ in the model.
	 */
	void refreshModelAssociations() {
		getModel().getSelectedAuthority().ifPresent(authority -> {
			final List<Permission> permissions = queryPermissions(authority);
			getModel().getSelectedAuthorityPermissions().removeAllItems();
			getModel().getSelectedAuthorityPermissions().addAll(permissions);
		});	
	}

	/**
	 * Refresh the current selected Authority_, but *not* its associations.
	 */
	private void refreshModelSelected() {
		getModel().getSelectedAuthority().ifPresent(authority -> getModel().setSelectedAuthority(authorityService.findOne(authority.getId()).orElse(null)));
	}

	/**	
	 * Set the query based on the String sent in the Event.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with a {@link String} query as {@link Event#getData()}.
	 */
	private void readList(Event<?> event) {
		final Object data = event.getData();

		if (data instanceof String) {
			final String filter = (String) event.getData();
			getModel().setQuery(filter);
		} else {
			getModel().setQuery(null);
		}

		refreshModelList();
		notifyComponents();
	}

	/**
	 * Read the Authority_ in the Event from the DataStore and set it as the current selected Authority_.
	 * If called with null, the current selected Authority_ will only be refreshed from the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Authority} or *null* as {@link Event#getData()}.
	 */
	private void readSelected(Event<?> event) {
		final Object data = event.getData();

		if (data instanceof Authority) {
			final Authority authority = (Authority) event.getData();
			getModel().setSelectedAuthority(authority);
			refreshModelSelected();
			refreshModelAssociations();
		} else if (data == null) {
			refreshModelSelected();
			refreshModelAssociations();
		} else {
			throw new IllegalArgumentException("The event cannot be of Class " + event.getData().getClass());
		}
		notifyComponents();
    }

	/**
	 * Notify all the Components.
	 */
	public void notifyComponents() {
		getEventbus().notify(getResponseKey(), Event.wrap(getModel()));
	}

	/**
	 * Get the RequestEntityKey for this Entity.
	 *
	 * @param event The disered event the Key will have.
	 * @return The RequestEntityKey with the chosen RequestEvent.
	 */
	public RequestEntityKey getRequestKey(RequestEvent event) {
		return new RequestEntityKey(event, Authority.class);
	}

	/**
	 * Get the ResponseEntityKey for this Entity.
	 *
	 * @return The ResponseEntityKey.
	 */
	public ResponseEntityKey getResponseKey() {
		return new ResponseEntityKey(Authority.class);
	}
}
