package de.muenchen.vaadin.guilib.security.controller;

import com.vaadin.spring.annotation.SpringComponent;
import com.vaadin.spring.annotation.UIScope;
import de.muenchen.eventbus.EventBus;
import de.muenchen.eventbus.events.Association;
import de.muenchen.eventbus.selector.entity.RequestEntityKey;
import de.muenchen.eventbus.selector.entity.RequestEvent;
import de.muenchen.eventbus.selector.entity.ResponseEntityKey;
import de.muenchen.vaadin.demo.apilib.local.Authority_;
import de.muenchen.vaadin.demo.apilib.local.User_;
import de.muenchen.vaadin.guilib.BaseUI;
import de.muenchen.vaadin.guilib.security.services.Authority_Service;
import de.muenchen.vaadin.guilib.security.services.User_Service;
import de.muenchen.vaadin.guilib.security.services.model.User_Datastore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.ResourceSupport;
import reactor.bus.Event;

import javax.annotation.PostConstruct;
import java.io.Serializable;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
@SpringComponent
@UIScope
public class User_ViewController implements Serializable{

	private static final long serialVersionUID = 1L;
	
	/**
	 * Logger
	 */
	private static final Logger LOG = LoggerFactory.getLogger(User_ViewController.class);
	
	/**
	 * Die User_Service Klasse
	 */
	@Autowired
	User_Service userService;
	
	/**
	 * Die Authority_Service Klasse
	 */
	@Autowired
	Authority_Service authorityService;
	
	private final User_Datastore model = new User_Datastore();
	

	@PostConstruct
	private void init() {
		initEventhandlers();
	}
	
	private EventBus getEventbus() {
        return BaseUI.getCurrentEventBus();
    }
	
	public User_Datastore getModel() {
		return model;
	}

	////////////////////////
	// Service Operations //
	////////////////////////

	/**
	 * Speichert ein {@link User_} Objekt in der Datenbank.
	 *
	 * @param user User_ der gespeichert werden soll
	 */
	public User_ save(User_ user) {
		return userService.create(user);
	}

	/**
	 * Zerstört die Verbindung zwischen einem User_ und seinem authoritys
	 *
	 * @param event
	 */
	private void releaseAuthorities(Authority_ event) {
		Link link = getModel().getSelectedUser().get().getLink(User_.Rel.authoritys.name());
		List<Link> authorities = authorityService.findAll(link)
				.stream()
				.map(Authority_::getId)
				.filter(id -> !id.equals(event.getId()))
				.collect(Collectors.toList());

		userService.setRelations(link, authorities);
	}
	
	
	/**
	 * Speichert eine beziehung als authoritys zu einem {@link Authority_} Objekt in der Datenbank.
	 *
	 * @param authoritiesEntity Authorities
	 * @return Authority_
	 */
	public void addUserAuthorities(Authority_ authoritiesEntity) {
		Link link = getModel().getSelectedUser().get().getLink(User_.Rel.authoritys.name());
		List<Link> authoritieslist = Stream.concat(
				authorityService.findAll(link)
						.stream()
						.map(Authority_::getId),
				Stream.of(authoritiesEntity.getId()))
	
				.collect(Collectors.toList());
	
		userService.setRelations(link, authoritieslist);
	}
	
	public List<Authority_> queryAuthorities(User_ entity) {
		return authorityService.findAll(entity.getLink(User_.Rel.authoritys.name())).stream().collect(Collectors.toList());
	}
	/**
	 * Speichert die Änderungen an einem {@link User_} Objekt in der Datenbank.
	 *
	 * @param entity User_
	 * @return User_
	 */
	public User_ updateUser(User_ entity) {
		return userService.update(entity);
	}

	/**
	 * Löscht ein {@link User_} Objekt.
	 *
	 * @param entity User_
	 */
	public void deleteUser(User_ entity) {
		userService.delete(entity.getId());
	}

	public List<User_> queryUser() {
		return userService.findAll().stream().collect(Collectors.toList());
	}

	public List<User_> queryUser(String query) {
		return userService.queryUser(query);
	}
	
	/////////////////////
	// Event Steuerung //
	/////////////////////

	/**
	 * Register all event handlers on the RequestEntityKey.
	 */
	private void initEventhandlers() {
		getEventbus().on(getRequestKey(RequestEvent.CREATE).toSelector(), this::create);
		getEventbus().on(getRequestKey(RequestEvent.DELETE).toSelector(), this::delete);
		getEventbus().on(getRequestKey(RequestEvent.UPDATE).toSelector(), this::update);
		getEventbus().on(getRequestKey(RequestEvent.ADD_ASSOCIATION).toSelector(), this::addAssociation);
		getEventbus().on(getRequestKey(RequestEvent.REMOVE_ASSOCIATION).toSelector(), this::removeAssociation);
		getEventbus().on(getRequestKey(RequestEvent.READ_LIST).toSelector(), this::readList);
		getEventbus().on(getRequestKey(RequestEvent.READ_SELECTED).toSelector(), this::readSelected);
	}

	/**
	 * Remove the specified Association from the specified Relation and update the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Association} as {@link Event#getData()}.
	 */
	void removeAssociation(Event<?> event) {
		final Object data = event.getData();
		if (data == null)
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Association.class)
			throw new IllegalArgumentException("The event must be of " + Association.class);

		final Association<?> association = (Association<?>) event.getData();
		final User_.Rel rel = User_.Rel.valueOf(association.getRel());
		
		if (User_.Rel.authoritys == rel) {
			Authority_ authorities = (Authority_) association.getAssociation();
			releaseAuthorities(authorities);
			getModel().getSelectedUserAuthorities().removeItem(authorities);
		}
		notifyComponents();
	}

	/**
	 * Add the specified Association to the specified Relation and update the DataStore.
	 * <p>	 
	 * If the {@link Association#getAssociation()} has no {@link ResourceSupport#getId()} the Resouce will be created
	 * on the DataStore first.
	 * </p>
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link Association} as {@link Event#getData()}.
	 */
	private void addAssociation(Event<?> event) {
		final Object data = event.getData();
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != Association.class)
			throw new IllegalArgumentException("The event must be of " + Association.class);

		final Association<?> association = (Association<?>) event.getData();

		final User_.Rel rel = User_.Rel.valueOf(association.getRel());
		if (User_.Rel.authoritys == rel) {
			Authority_ authorities = (Authority_) association.getAssociation();
			// If Authorities has no ID he has to be created in the backend
			if (authorities.getId() == null) {
				authorities = authorityService.create(authorities);
			}
			addUserAuthorities(authorities);
			getModel().getSelectedUserAuthorities().addBean(authorities);
		}
		refreshModelAssociations();
		notifyComponents();
	}

	/**	
	 * Create a new Buerger on the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link User_} as {@link Event#getData()}.
	 */
	private void create(Event<?> event) {
		final Object data = event.getData();
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != User_.class)
			throw new IllegalArgumentException("The event must be of " + User_.class);
		final User_ user = (User_) event.getData();
		final User_ fromREST = userService.create(user);
		getModel().getUsers().addBean(fromREST);
		notifyComponents();
	}


	/**
	 * Delete the User_ on the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link User_} as {@link Event#getData()}.
	 */
	private void delete(Event<?> event) {
		final Object data = event.getData();
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != User_.class)
			throw new IllegalArgumentException("The event must be of " + User_.class);
		final User_ user = (User_) event.getData();
		if (user.getId() == null)
			throw new IllegalArgumentException("The User_ must have an ID.");
		userService.delete(user.getId());
		getModel().getSelectedUser().ifPresent(selectedUser -> {
			if (selectedUser.equals(user)) {
				getModel().setSelectedUser(null);
				// reset all selected relations
				getModel().getSelectedUserAuthorities().removeAllItems();
			}
		});
		getModel().getUsers().removeItem(user);
		notifyComponents();
	}

	/**
	 * Update the User_ on the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link User_} as {@link Event#getData()}.
	 */
	private void update(Event<?> event) {
		final Object data = event.getData();	 
		if (data == null) 
			throw new NullPointerException("Event data must not be null!");
		if (data.getClass() != User_.class)
			throw new IllegalArgumentException("The event must be of " + User_.class);
		final User_ user = (User_) event.getData();
		if (user.getId() == null)
			throw new IllegalArgumentException("The User_ must have an ID.");
		final User_ fromREST = userService.update(user);
		refreshModelSelected();
		getModel().getUsers().addBean(fromREST);
		notifyComponents();
	}

	/**
	 * Refresh the {@link User_Datastore#users} list from the DataStore.
	 * <p/>	
	 * <p>
	 * This method also filters by the query (ifPresent).
	 * </p>
	 */
	private void refreshModelList() {
		final Optional<String> query = getModel().getQuery();
		if (query.isPresent()) {
			getModel().getUsers().removeAllItems();
			getModel().getUsers().addAll(queryUser(query.get()));
		} else {
			getModel().getUsers().removeAllItems();
			getModel().getUsers().addAll(queryUser());
		}
	}

	/**
	 * Refresh *all* the associations of the selected User_ in the model.
	 */
	void refreshModelAssociations() {
		getModel().getSelectedUser().ifPresent(user -> {
			final List<Authority_> authorities = queryAuthorities(user);
			getModel().getSelectedUserAuthorities().removeAllItems();
			getModel().getSelectedUserAuthorities().addAll(authorities);
		});	
	}

	/**
	 * Refresh the current selected User_, but *not* its associations.
	 */
	private void refreshModelSelected() {
		getModel().getSelectedUser().ifPresent(user -> getModel().setSelectedUser(userService.findOne(user.getId()).orElse(null)));
	}

	/**	
	 * Set the query based on the String sent in the Event.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with a {@link String} query as {@link Event#getData()}.
	 */
	private void readList(Event<?> event) {
		final Object data = event.getData();

		if (data instanceof String) {
			final String filter = (String) event.getData();
			getModel().setQuery(filter);
		} else {
			getModel().setQuery(null);
		}

		refreshModelList();
		notifyComponents();
	}

	/**
	 * Read the User_ in the Event from the DataStore and set it as the current selected User_.
	 * If called with null, the current selected User_ will only be refreshed from the DataStore.
	 * Update the Model and send it on the ResponseEntityKey if necessary.
	 *
	 * @param event The event with an {@link User_} or *null* as {@link Event#getData()}.
	 */
	private void readSelected(Event<?> event) {
		final Object data = event.getData();

		if (data instanceof User_) {
			final User_ user = (User_) event.getData();
			getModel().setSelectedUser(user);
			refreshModelSelected();
			refreshModelAssociations();
		} else if (data == null) {
			refreshModelSelected();
			refreshModelAssociations();
		} else {
			throw new IllegalArgumentException("The event cannot be of Class " + event.getData().getClass());
		}
		notifyComponents();
    }

	/**
	 * Notify all the Components.
	 */
	public void notifyComponents() {
		getEventbus().notify(getResponseKey(), Event.wrap(getModel()));
	}

	/**
	 * Get the RequestEntityKey for this Entity.
	 *
	 * @param event The disered event the Key will have.
	 * @return The RequestEntityKey with the chosen RequestEvent.
	 */
	public RequestEntityKey getRequestKey(RequestEvent event) {
		return new RequestEntityKey(event, User_.class);
	}

	/**
	 * Get the ResponseEntityKey for this Entity.
	 *
	 * @return The ResponseEntityKey.
	 */
	public ResponseEntityKey getResponseKey() {
		return new ResponseEntityKey(User_.class);
	}
}
