package de.muenchen.kvr.buergerverwaltung.buerger.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.Arrays;
import java.text.ParseException;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.services.businessactions.TestDatenBusinessActionService;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.MoeglicheStaatsangehoerigkeiten_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Augenfarben_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Passtyp_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Buerger_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.rest.Buerger_Repository;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Adresse_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.rest.Adresse_Repository;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.AdresseExtern_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.AdresseIntern_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Pass_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.rest.Pass_Repository;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Sachbearbeiter_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.rest.Sachbearbeiter_Repository;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Wohnung_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.rest.Wohnung_Repository;

import de.muenchen.service.security.UserInfo;

/**
 * Provides a service to execute business-actions.
 * If used as generated by GAIA this service will be autowired and called by BusinessActionController.
 */
@Service
public class TestDatenBusinessActionServiceImpl implements TestDatenBusinessActionService {
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	@Autowired
	Buerger_Repository buergerRepo;
	@Autowired
	Adresse_Repository adresseRepo;
	@Autowired
	Pass_Repository passRepo;
	@Autowired
	Sachbearbeiter_Repository sachbearbeiterRepo;
	@Autowired
	Wohnung_Repository wohnungRepo;

	public void testdatenErzeugen(){
		
		//insert example data for Buerger_
		Buerger_ buerger = new Buerger_();
		buerger.setVorname("Peter");
		buerger.setNachname("Müller");
		try {
			buerger.setGeburtstag(new java.text.SimpleDateFormat("dd.mm.yyyy").parse("07.09.1995"));
		} catch (ParseException e) {
			e.printStackTrace();
		}
		buerger.setAugenfarbe(Augenfarben_.braun);
		buerger.setTelefonnummer(8912345L);
		buerger.setEmail("p.mueller@muenchen.de");
		buerger.setLebendig(false);
		buerger.setStaatsangehoerigkeiten(new java.util.ArrayList<>(Arrays.asList(MoeglicheStaatsangehoerigkeiten_.deutsch)));
		buerger.setEigenschaften(new java.util.ArrayList<>(Arrays.asList("gehtnich")));
		buerger.setOid(1L);
		
		//insert example data for Adresse_
		Adresse_ adresse = new Adresse_();
		adresse.setOid(1L);
		
		//insert example data for AdresseExtern_
		AdresseExtern_ adresseExtern = new AdresseExtern_();
		adresseExtern.setStrasse("Allgäuer Straße");
		adresseExtern.setHausnummer(666L);
		adresseExtern.setPlz(12345L);
		adresseExtern.setOrt("Allgäu");
		
		//insert example data for AdresseIntern_
		AdresseIntern_ adresseIntern = new AdresseIntern_();
		adresseIntern.setStrassenSchluessel(1234567890L);
		adresseIntern.setHausnummer(13L);
		
		//insert example data for Pass_
		Pass_ pass = new Pass_();
		pass.setPassNummer(56473829L);
		pass.setTyp(Passtyp_.personalausweis);
		pass.setKode("lösche gerne Sachen");
		pass.setGroesse(10L);
		pass.setBehoerde("Narnia");
		pass.setOid(1L);
		
		//insert example data for Sachbearbeiter_
		Sachbearbeiter_ sachbearbeiter = new Sachbearbeiter_();
		sachbearbeiter.setTelefon(987654321L);
		sachbearbeiter.setFax(987654320L);
		sachbearbeiter.setFunktion("löschen");
		sachbearbeiter.setOrganisationseinheit("it@m");
		sachbearbeiter.setOid(1L);
		
		//insert example data for Wohnung_
		Wohnung_ wohnung = new Wohnung_();
		wohnung.setStock("255");
		wohnung.setAusrichtung("nordnordost");
		wohnung.setOid(1L);
		
		// Set relations
		buerger.setKinder(new java.util.ArrayList<>(Arrays.asList(buerger)));
		buerger.setPartner(buerger);
		buerger.setPass(pass);
		buerger.setSachbearbeiter(new java.util.ArrayList<>(Arrays.asList(sachbearbeiter)));
		buerger.setWohnungen(wohnung);
		wohnung.setAdresse(new java.util.ArrayList<>(Arrays.asList(adresse)));
		
		//Save all example Entities in an order that won't cause errors
		adresseRepo.save(adresse);
		passRepo.save(pass);
		sachbearbeiterRepo.save(sachbearbeiter);
		buergerRepo.save(buerger);
		wohnungRepo.save(wohnung);
		}

}
