spring:
  profiles:
    active: local
  cloud:
    config:
      discovery:
        enabled: true
eureka.client.fetchRegistry: false
---
spring:
  profiles: local
---
spring:
  profiles: docker
---
spring:
  profiles: vm

