package de.muenchen.kvr.buergerverwaltung.buerger.service.services.event;

import org.springframework.stereotype.Service;

import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Buerger_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.services.event.Buerger_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Buerger_EventListener.
 */
@Service
public class Buerger_EventServiceImpl implements Buerger_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Buerger_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Buerger_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Buerger_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Buerger_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Buerger_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Buerger_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Buerger_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Buerger_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Buerger_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Buerger_ parent, Object linked) {
		// Add your logic here.
	}
}
