package de.muenchen.kvr.buergerverwaltung.buerger.service.services.event;

import org.springframework.stereotype.Service;

import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.domain.Pass_;
import de.muenchen.kvr.buergerverwaltung.buerger.service.gen.services.event.Pass_EventService;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by GAIA this service will be autowired and called by Pass_EventListener.
 */
@Service
public class Pass_EventServiceImpl implements Pass_EventService{
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Pass_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Pass_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Pass_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Pass_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Pass_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Pass_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Pass_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Pass_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Pass_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Pass_ parent, Object linked) {
		// Add your logic here.
	}
}
