package de.muenchen.auth.repositories;


import de.muenchen.auth.entities.User;
import de.muenchen.auth.services.UserResourceService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.ResourceProcessor;
import org.springframework.stereotype.Component;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * This RessourceProcessor can alter Resources, before they are sent out.
 */
@Component
public class UserResourceProcessor implements ResourceProcessor<Resource<User>> {

    /**
     * Service for processing User_ entities.
     */
    @Autowired
    UserResourceService resourceService;

    @Override
    public Resource<User> process(Resource<User> resource) {
        // Hand the resource to the service.
        resourceService.process(resource);
        return resource;
    }

}

