package de.muenchen.kvr.buergerverwaltung.buerger.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class AdresseExtern_DTO {
	
	private String strasse;
	
	private long hausnummer;
	
	private long plz;
	
	private String ort;
	
	// Getters and Setters
	public String getStrasse(){
		return strasse;
	}
	public void setStrasse(String strasse){
		this.strasse = strasse;
	}
	
	public long getHausnummer(){
		return hausnummer;
	}
	public void setHausnummer(long hausnummer){
		this.hausnummer = hausnummer;
	}
	
	public long getPlz(){
		return plz;
	}
	public void setPlz(long plz){
		this.plz = plz;
	}
	
	public String getOrt(){
		return ort;
	}
	public void setOrt(String ort){
		this.ort = ort;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"strasse\": \"%s\", \"hausnummer\": \"%s\", \"plz\": \"%s\", \"ort\": \"%s\"}", getClass(),
	   		this.strasse,
	   		this.hausnummer,
	   		this.plz,
	   		this.ort);
	}
}
