package de.muenchen.kvr.buergerverwaltung.buerger.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Adresse_DTO extends BaseEntity {
	
	private AdresseIntern_DTO interneAdresse;
	
	private AdresseExtern_DTO externeAdresse;
	
	// Getters and Setters
	public AdresseIntern_DTO getInterneAdresse(){
		return interneAdresse;
	}
	public void setInterneAdresse(AdresseIntern_DTO value){
		this.interneAdresse = value;
	}
	
	public AdresseExtern_DTO getExterneAdresse(){
		return externeAdresse;
	}
	public void setExterneAdresse(AdresseExtern_DTO value){
		this.externeAdresse = value;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {}", getClass());
	}
}
