package de.muenchen.vaadin.demo.apilib.local;

/*
 * This file will NOT be overwritten by GAIA.
 * This file was automatically generated by GAIA.
 */

import org.springframework.hateoas.ResourceSupport;

import javax.validation.constraints.NotNull;
import java.util.stream.Stream;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_ extends ResourceSupport {
	
	@NotNull
	private String permission;
	
	public Permission_(){}
	
	/**
     * Create a new Permission_ with the  permission.
     *
     * @param permission the permission of the Permission_.
     */
    public Permission_( String permission) {
        this.setPermission(permission);
    }
	
	// Getters and Setters
	public String getPermission(){
		return permission;
	}
	
	public void setPermission(String permission){
		this.permission = permission;
	}
	
	 /**
      * A simple Enum for all the Fields of this Permission_.
      * <p>
      *     You can use {@link Field#name()} for the String.
      * </p>
      */
	public enum Field {
        permission;

        private final boolean field;

        Field() {
			this(true);
		}

		Field(boolean field) {
			this.field = field;
		}

		public boolean isField() {
			return field;
		}

		public static String[] getProperties() {
			return Stream.of(values()).filter(Field::isField).map(Field::name).toArray(String[]::new);
		}
	}
	
	 /**
	  * A simple Enum for all the Relations ({@link Permission_#getLink(String)} of the Permission_.
	  * <p>
	  *     You can use {@link Rel#name()} for the String.
	  * </p>
	  */
	 public enum Rel {
	 	;
    }
	
	@Override
	public String toString(){
		return permission;
	}
}
