package de.muenchen.vaadin.services;


import de.muenchen.vaadin.demo.api.local.Buerger;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class BuergerFallbackDataGenerator {

    /** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */


    /**
     * Generiert Fallback-Daten für Methoden, die einen einzelnen Buerger zurückliefern.
     *
     * @return Generierter fallback-Wert
     */
    public static Buerger createBuergerFallback() {
        return null;
    }

    /**
     * Generiert Fallback-Daten für Methoden, die eine Liste von Buerger zurückliefern.
     *
     * @return Generierter fallback-Wert
     */
    public static List<Buerger> createBuergersFallback() {
        return new ArrayList<>();
    }

    /**
     * Generiert Fallback-Daten für Methoden, die ein Optional von Buerger zurückliefern.
     *
     * @return Generierter fallback-Wert
     */
    public static Optional<Buerger> createOptionalBuergerFallback() {
        return Optional.empty();
    }

}
