package de.muenchen.vaadin.services;

import de.muenchen.vaadin.demo.api.local.Buerger;
import org.springframework.hateoas.Link;

import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
/**
 * Service zum Verwalten von Buerger aus der GUI heraus.
 */
public interface BuergerService {
    Buerger create(Buerger buerger);

    Buerger update(Buerger buerger);

    boolean delete(Link link);

    List<Buerger> findAll();

    List<Buerger> findAll(Link relation);

    Optional<Buerger> findOne(Link link);

    List<Buerger> queryBuerger(String query);

    boolean setRelations(Link link, List<Link> relations);

    boolean setRelation(Link link, Link relation);
}
