package de.muenchen.vaadin.services;

import com.vaadin.server.Page;
import com.vaadin.spring.annotation.SpringComponent;
import com.vaadin.spring.annotation.UIScope;
import de.muenchen.vaadin.demo.api.local.Buerger;
import de.muenchen.vaadin.demo.api.rest.BuergerRestClient;
import de.muenchen.vaadin.demo.api.rest.BuergerRestClientImpl;
import de.muenchen.vaadin.demo.apilib.services.SecurityService;
import de.muenchen.vaadin.demo.i18nservice.I18nPaths;
import de.muenchen.vaadin.demo.i18nservice.buttons.SimpleAction;
import de.muenchen.vaadin.guilib.components.GenericErrorNotification;
import de.muenchen.vaadin.guilib.components.GenericSuccessNotification;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.Link;
import org.springframework.http.HttpStatus;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestTemplate;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.Callable;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import static de.muenchen.vaadin.demo.i18nservice.I18nPaths.getNotificationPath;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
@SpringComponent @UIScope
public class BuergerServiceImpl implements BuergerService, Serializable {

    private static final Logger LOG = LoggerFactory.getLogger(BuergerServiceImpl.class);
    public static final String TIMEOUT_I18N = "timeout";
    public static final int TIMEOUT_VAL = 5;

    private BuergerRestClient client;
    private RestTemplate template;
    private SecurityService securityService;
    private BuergerI18nResolver resolver;

    @Autowired
    public BuergerServiceImpl(InfoService infoService, SecurityService securityService, BuergerI18nResolver resolver) {
        this.securityService=securityService;
        this.client = new BuergerRestClientImpl(getTemplate(), infoService.getBaseUri());
        this.resolver = resolver;
    }

    /**
     * creates one Buerger
     * @param buerger the one who shall be createed
     * @return buerger
     */
    @Override
    public Buerger create(Buerger buerger) {
        Buerger returnBuerger;
        Future<Buerger> result = Executors.newCachedThreadPool().submit(() -> client.create(buerger));
        try {
            returnBuerger = result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
            showSuccessNotification(I18nPaths.NotificationType.success, SimpleAction.create);
        } catch (HttpClientErrorException e) {
            returnBuerger = BuergerFallbackDataGenerator.createBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.create);
        } catch (TimeoutException e) {
            returnBuerger = BuergerFallbackDataGenerator.createBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.create, TIMEOUT_I18N);
        } catch (Exception e) {
            returnBuerger = BuergerFallbackDataGenerator.createBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.create);
        } finally {
            result.cancel(true);
        }
        return returnBuerger;
    }

    /**
     * updates one Buerger
     * @param buerger the one who shall be updated
     * @return buerger
     */
    @Override
    public Buerger update(Buerger buerger) {
        Buerger returnBuerger;
        Future<Buerger> result = Executors.newCachedThreadPool().submit(() -> client.update(buerger));
        try {
            returnBuerger = result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
            showSuccessNotification(I18nPaths.NotificationType.success, SimpleAction.update);
        } catch (HttpClientErrorException e) {
            returnBuerger = BuergerFallbackDataGenerator.createBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.update);
        } catch (TimeoutException e) {
            returnBuerger = BuergerFallbackDataGenerator.createBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.update, TIMEOUT_I18N);
        } catch (Exception e) {
            returnBuerger = BuergerFallbackDataGenerator.createBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.update);
        } finally {
            result.cancel(true);
        }
        return returnBuerger;
    }

    /**
     * Method to delete a certain link
     * @param link the link
     * @return successful
     */
    @Override
    public boolean delete(Link link) {
        Future<?> result = Executors.newCachedThreadPool().submit(() -> client.delete(link));
        try {
            result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
            showSuccessNotification(I18nPaths.NotificationType.success, SimpleAction.delete);
            return true;
        } catch (HttpClientErrorException e) {
            LOG.error(e.getMessage());
            HttpStatus statusCode = e.getStatusCode();
            if (statusCode.equals(HttpStatus.CONFLICT) || statusCode.equals(HttpStatus.NOT_FOUND))
                showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.delete, statusCode.toString());
            else
                showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.delete);
            return false;
        } catch (TimeoutException e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.delete, TIMEOUT_I18N);
            return false;
        } catch (Exception e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.delete);
            return false;
        } finally {
            result.cancel(true);
        }
    }

    /**
     * Returns all Buerger
     * @return buergers the results
     */
    @Override
    public List<Buerger> findAll() {
        List<Buerger> buergers;
        Future<List<Buerger>> result = Executors.newCachedThreadPool().submit((Callable<List<Buerger>>) client::findAll);
        try {
            buergers = result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
            return buergers;
        } catch (HttpClientErrorException e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } catch (TimeoutException e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read, TIMEOUT_I18N);
        } catch (Exception e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } finally {
            result.cancel(true);
        }
        return buergers;
    }

    /**
     * Returns all Buerger of a specified relation
     * @param relation the relation
     * @return buergers the results
     */
    @Override
    public List<Buerger> findAll(Link relation) {
        List<Buerger> buergers;
        Future<List<Buerger>> result = Executors.newCachedThreadPool().submit(() -> client.findAll(relation));
        try {
            buergers = result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
        } catch (HttpClientErrorException e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } catch (TimeoutException e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read, TIMEOUT_I18N);
        } catch (Exception e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } finally {
            result.cancel(true);
        }
        return buergers;
    }

    /**
     * Returns an Optional of Buerger to one Link
     * @param link the link
     * @return the found Buerger
     */
    @Override
    public Optional<Buerger> findOne(Link link) {
        Optional<Buerger> buerger;
        Future<Optional<Buerger>> result = Executors.newCachedThreadPool().submit(() -> client.findOne(link));
        try {
            buerger = result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
        } catch (HttpClientErrorException e) {
            buerger = BuergerFallbackDataGenerator.createOptionalBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } catch (TimeoutException e) {
            buerger = BuergerFallbackDataGenerator.createOptionalBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read, TIMEOUT_I18N);
        } catch (Exception e) {
            buerger = BuergerFallbackDataGenerator.createOptionalBuergerFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } finally {
            result.cancel(true);
        }
        return buerger;
    }

    /**
     * Query to given string
     * @param query
     * @return buergers the results
     */
    @Override
    public List<Buerger> queryBuerger(String query) {
        List<Buerger> buergers;
        Future<List<Buerger>> result = Executors.newCachedThreadPool().submit(() -> client.findFullTextFuzzy(query));
        try {
            buergers = result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
        } catch (HttpClientErrorException e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } catch (TimeoutException e){
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read, TIMEOUT_I18N);
        } catch (Exception e) {
            buergers = BuergerFallbackDataGenerator.createBuergersFallback();
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.read);
        } finally {
            result.cancel(true);
        }
        return buergers;
    }

    /**
     * Sets relations to entities
     * @param link the endpoint of the relation
     * @param links collection of links that are set to be related
     * @return successful
     */
    @Override
    public boolean setRelations(Link link, List<Link> links) {
        Future<?> result = Executors.newCachedThreadPool().submit(() -> client.setRelations(link, links));
        try {
            result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
            showSuccessNotification(I18nPaths.NotificationType.success, SimpleAction.association);
            return true;
        } catch (HttpClientErrorException e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.association);
            return false;
        } catch (TimeoutException e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.association, TIMEOUT_I18N);
            return false;
        } catch (Exception e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.association);
            return false;
        } finally {
            result.cancel(true);
        }
    }

    /**
     * Sets a relation to an entity
     * @param link the endpoint of the relation
     * @param relation the link that is set to be related
     * @return successful
     */
    @Override
    public boolean setRelation(Link link, Link relation) {
        Future<?> result = Executors.newCachedThreadPool().submit(() -> client.setRelation(link, relation));
        try {
            result.get(TIMEOUT_VAL, TimeUnit.SECONDS);
            showSuccessNotification(I18nPaths.NotificationType.success, SimpleAction.association);
            return true;
        } catch (HttpClientErrorException e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.association);
            return false;
        } catch (TimeoutException e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.association, TIMEOUT_I18N);
            return false;
        } catch (Exception e) {
            LOG.error(e.getMessage());
            showErrorNotification(I18nPaths.NotificationType.error, SimpleAction.association);
            return false;
        } finally {
            result.cancel(true);
        }
    }

    /**
     * Gets the resttemplate from the security if not present
     * @return resttemplate of this session
     */
    public RestTemplate getTemplate() {
        if (template != null) {
            return template;
        }
        return securityService.getRestTemplate().orElse(null);
    }

    /**
     * Shows a success notification
     * @param type the type of the notification
     * @param action the type of action performed
     */
    private void showSuccessNotification(I18nPaths.NotificationType type, SimpleAction action) {
        GenericSuccessNotification succes = new GenericSuccessNotification(
                resolver.resolveRelative(getNotificationPath(type, action, I18nPaths.Type.label)),
                resolver.resolveRelative(getNotificationPath(type, action, I18nPaths.Type.text)));
        succes.show(Page.getCurrent());
    }

    /**
     * Shows an error notification
     * @param type the type of the notification
     * @param action the type of action performed
     */
    private void showErrorNotification(I18nPaths.NotificationType type, SimpleAction action) {
        GenericErrorNotification succes = new GenericErrorNotification(
                resolver.resolveRelative(getNotificationPath(type, action, I18nPaths.Type.label)),
                resolver.resolveRelative(getNotificationPath(type, action, I18nPaths.Type.text)));
        succes.show(Page.getCurrent());
    }

    /**
     * Shows an error notification specified by a status code
     * @param type the type of the notification
     * @param action the type of action performed
     * @param statusCode the status code
     */
    private void showErrorNotification(I18nPaths.NotificationType type, SimpleAction action, String statusCode) {
        GenericErrorNotification succes = new GenericErrorNotification(
                resolver.resolveRelative(getNotificationPath(type, action, I18nPaths.Type.label, statusCode)),
                resolver.resolveRelative(getNotificationPath(type, action, I18nPaths.Type.text, statusCode)));
        succes.show(Page.getCurrent());
    }
}
