package de.muenchen.vaadin.demo.apilib.rest;

import de.muenchen.vaadin.demo.apilib.local.Authority_;
import org.springframework.hateoas.Link;

import java.util.Collection;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public interface Authority_RestClient {

    /**
     * The name of the Base Endpoint
     */
    public static final String AUTHORITYS = "authorities";

    /**
     * Get all the Authoritys (with matching tenancy).
     *
     * @return a List of all Authoritys.
     */
    List<Authority_> findAll();

    /**
     * Get all the Authoritys (with matching tenancy) on a specific endpoint.
     * <p>
     *     For example: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * @param relation
     * @return
     */
    List<Authority_> findAll(Link relation);
    
    /**
     * Get all Authority matched with string due to fuzzy search.
     * @param filter the string for the query
     * @return
     */
    List<Authority_> findFullTextFuzzy(String filter);

    /**
     * Try to find one Authority (with matching tenancy) by its ID / self relation.
     *
     * @param link The ID / self relation of the Authority_.
     * @return an optional of the Authority_.
     */
    Optional<Authority_> findOne(Link link);

    /**
     * Set all the relations, specified by links, on a specific relation endpoint.
     * <p>
     * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * <p>
     * This method will always (re-) set the associations. The add or delete
     * functionality is not provided at RestClient level.
     * </p>
     *
     * @param endpoint The endpoint of the relation.
     * @param links    The links that are set to be related.
     */
    void setRelations(Link endpoint, Collection<Link> links);
	/**
	 * Set the relation, specified by @relation, on a specific relation endpoint.
	 * <p>
	 * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
	 * </p>
	 * <p>
	 * This method will always (re-) set the association. The add or delete
	 * functionality is not provided at RestClient level.
	 * </p>
	 *
	 * @param endpoint The endpoint of the relation.
	 * @param relation    The link that is set to be related.
	 */
	void setRelation(Link endpoint, Link relation);
    /**
     * Create a new Authority_, the returned Authority_ will have the Links and its ID.
     * @param authority The Authority_ to create, it must not contain any links.
     * @return the created Authority_ (with ID).
     */
    Authority_ create(Authority_ authority);

    /**
     * Update the fields of a Authority_ by the {@link Authority_#getId()}.
     *
     * @param authority The updated Authority_ that will be saved.
     * @return the updated version from the REST Server.
     */
    Authority_ update(Authority_ authority);

    /**
     * Try to delete an ID.
     * @param id The link to the id.
     */
    void delete(Link id);
}
