package de.muenchen.vaadin.demo.apilib.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import de.muenchen.vaadin.demo.apilib.domain.Authority_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Authority_Resource extends Resource<Authority_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<Authority_Resource>> LIST = new ParameterizedTypeReference<Resources<Authority_Resource>>() {
    };

    /**
     * Create a new Resource with a blank Authority_DTO.
     */
    public Authority_Resource() {
        super(new Authority_DTO());
    }

    /**
     * Create a new Resource from  a Authority_DTO and multiple Resources.
     * @param content The Authority_DTO
     * @param links The links to add to the resource
     */
    public Authority_Resource(Authority_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a Authority_DTO and multiple Resources.
     * @param content The Authority_DTO
     * @param links The links to add to the resource
     */
    public Authority_Resource(Authority_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
