package de.muenchen.vaadin.demo.apilib.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import de.muenchen.vaadin.demo.apilib.domain.Permission_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Permission_Resource extends Resource<Permission_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<Permission_Resource>> LIST = new ParameterizedTypeReference<Resources<Permission_Resource>>() {
    };

    /**
     * Create a new Resource with a blank Permission_DTO.
     */
    public Permission_Resource() {
        super(new Permission_DTO());
    }

    /**
     * Create a new Resource from  a Permission_DTO and multiple Resources.
     * @param content The Permission_DTO
     * @param links The links to add to the resource
     */
    public Permission_Resource(Permission_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a Permission_DTO and multiple Resources.
     * @param content The Permission_DTO
     * @param links The links to add to the resource
     */
    public Permission_Resource(Permission_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
