package de.muenchen.vaadin.demo.apilib.rest;

import de.muenchen.vaadin.demo.apilib.local.User;
import org.springframework.hateoas.Link;

import java.util.Collection;
import java.util.List;
import java.util.Optional;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public interface User_RestClient {

    /**
     * The name of the Base Endpoint
     */
    public static final String USERS = "users";

    /**
     * Get all the Users (with matching tenancy).
     *
     * @return a List of all Users.
     */
    List<User> findAll();

    /**
     * Get all the Users (with matching tenancy) on a specific endpoint.
     * <p>
     *     For example: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * @param relation
     * @return
     */
    List<User> findAll(Link relation);
    
    /**
     * Get all User matched with string due to fuzzy search.
     * @param filter the string for the query
     * @return
     */
    List<User> findFullTextFuzzy(String filter);

    /**
     * Try to find one User (with matching tenancy) by its ID / self relation.
     *
     * @param link The ID / self relation of the User_.
     * @return an optional of the User_.
     */
    Optional<User> findOne(Link link);

    /**
     * Set all the relations, specified by links, on a specific relation endpoint.
     * <p>
     * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
     * </p>
     * <p>
     * This method will always (re-) set the associations. The add or delete
     * functionality is not provided at RestClient level.
     * </p>
     *
     * @param endpoint The endpoint of the relation.
     * @param links    The links that are set to be related.
     */
    void setRelations(Link endpoint, Collection<Link> links);
	/**
	 * Set the relation, specified by @relation, on a specific relation endpoint.
	 * <p>
	 * Example for an Endpoint: <code>http://localhost:80/entitys/1/attribute</code>
	 * </p>
	 * <p>
	 * This method will always (re-) set the association. The add or delete
	 * functionality is not provided at RestClient level.
	 * </p>
	 *
	 * @param endpoint The endpoint of the relation.
	 * @param relation    The link that is set to be related.
	 */
	void setRelation(Link endpoint, Link relation);
    /**
     * Create a new User_, the returned User_ will have the Links and its ID.
     * @param user The User_ to create, it must not contain any links.
     * @return the created User_ (with ID).
     */
    User create(User user);

    /**
     * Update the fields of a User_ by the {@link User#getId()}.
     *
     * @param user The updated User_ that will be saved.
     * @return the updated version from the REST Server.
     */
    User update(User user);

    /**
     * Try to delete an ID.
     * @param id The link to the id.
     */
    void delete(Link id);
}
