package de.muenchen.kvr.buergerverwaltung.buerger.client.domain;

import de.muenchen.vaadin.demo.apilib.domain.BaseEntity;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Pass_DTO extends BaseEntity {
	
	private long passNummer;
	
	private Passtyp_ typ;
	
	private String kode;
	
	private long groesse;
	
	private String behoerde;
	
	// Getters and Setters
	public long getPassNummer(){
		return passNummer;
	}
	public void setPassNummer(long passNummer){
		this.passNummer = passNummer;
	}
	
	public Passtyp_ getTyp(){
		return typ;
	}
	public void setTyp(Passtyp_ typ){
		this.typ = typ;
	}
	
	public String getKode(){
		return kode;
	}
	public void setKode(String kode){
		this.kode = kode;
	}
	
	public long getGroesse(){
		return groesse;
	}
	public void setGroesse(long groesse){
		this.groesse = groesse;
	}
	
	public String getBehoerde(){
		return behoerde;
	}
	public void setBehoerde(String behoerde){
		this.behoerde = behoerde;
	}
	
	@Override
	public String toString() {
	   	return String.format("%s = {\"passNummer\": \"%s\", \"typ\": \"%s\", \"kode\": \"%s\", \"groesse\": \"%s\", \"behoerde\": \"%s\"}", getClass(),
	   		this.passNummer,
	   		this.typ,
	   		this.kode,
	   		this.groesse,
	   		this.behoerde);
	}
}
