package de.muenchen.kvr.buergerverwaltung.buerger.client.rest;

import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.Adresse_DTO;
import de.muenchen.kvr.buergerverwaltung.buerger.client.hateoas.Adresse_Assembler;
import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Adresse_;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.MediaTypes;
import org.springframework.hateoas.client.Traverson;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestTemplate;

import java.net.URI;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Adresse_RestClientImpl implements Adresse_RestClient {
	
	public static final String FIND_FULL_TEXT_FUZZY = "findFullTextFuzzy";
	
	public static final String SEARCH = "search";
	
	/** Used to follow HATEOAS relations. */
    private final Traverson traverson;
    
    /** The restTemplate used for the HTTP Requests. */
    private final RestTemplate restTemplate;
    
    /** Assembler to switch from Adresse_DTO Resource to Adresse_ and vice versa. */
    private final Adresse_Assembler adresseAssembler = new Adresse_Assembler();
	
	/**
	 * Create a new Adresse_RestClient by RestTemplate of the server.
     * @param restTemplate The restTemplate for the HTTP Requests.
     * @param basePath The base URI of the REST Server.
     */
    public Adresse_RestClientImpl(RestTemplate restTemplate, final URI basePath) {
        this.restTemplate = restTemplate;
        traverson = new Traverson(basePath, MediaTypes.HAL_JSON);
        traverson.setRestOperations(restTemplate);
    }
	
	@Override
	public List<Adresse_> findFullTextFuzzy(String filter) {
		return traverson.follow(ADRESSES, SEARCH, FIND_FULL_TEXT_FUZZY)
				.withTemplateParameters(Collections.singletonMap("q", filter))
				.toObject(Adresse_Resource.LIST).getContent()
				.stream()
				.map(adresseAssembler::toBean)
				.collect(Collectors.toList());
	}
	
	@Override
	public List<Adresse_> findAll() {  
		return traverson
				.follow(ADRESSES)
				.toObject(Adresse_Resource.LIST).getContent()
				
				.stream()
				.map(adresseAssembler::toBean)
				.collect(Collectors.toList());
	}
	
	@Override
	public List<Adresse_> findAll(Link relation) {
		URI uri = URI.create(relation.getHref());
		return restTemplate
		 		.exchange(uri, HttpMethod.GET, null, Adresse_Resource.LIST)
		 		.getBody()
		 		.getContent()
		 		
		 		.stream()
		 		.map(adresseAssembler::toBean)
		 		.collect(Collectors.toList());
	}
		
	@Override
	public Optional<Adresse_> findOne(Link link) {
	     URI uri = URI.create(link.getHref());
		Adresse_Resource resource = restTemplate
				.exchange(uri, HttpMethod.GET, null, Adresse_Resource.class)
				.getBody();
				
		return Optional.of(adresseAssembler.toBean(resource));
	}
	
	@Override
	public void setRelations(Link endpoint, Collection<Link> links) {
		String relations = links.stream().map(Link::getHref).collect(Collectors.joining("\n"));
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(new MediaType("text", "uri-list"));
		restTemplate.exchange(URI.create(endpoint.getHref()), HttpMethod.PUT, new HttpEntity<>(relations, headers), Void.class);
	}
	
	@Override
    public void setRelation(Link endpoint, Link relation) {
    	Optional<Link> rel = Optional.ofNullable(relation);
		if (rel.isPresent()) {
			HttpHeaders headers = new HttpHeaders();
			headers.setContentType(new MediaType("text", "uri-list"));
			restTemplate.exchange(URI.create(endpoint.getHref()), HttpMethod.PUT, new HttpEntity<>(rel.map(Link::getHref).get(), headers), Void.class);
		} else {
			this.delete(endpoint);
		}
    }

		
	@Override
	public Adresse_ create(Adresse_ adresse) {
		URI uri = URI.create(
		traverson.follow(ADRESSES).asLink().getHref());
			Adresse_DTO adresseDTO = adresseAssembler.toResource(adresse).getContent();
			Adresse_Resource resource = restTemplate.exchange(uri, HttpMethod.POST, new HttpEntity<>(adresseDTO), Adresse_Resource.class).getBody();
			return adresseAssembler.toBean(resource);
	}
	
	@Override
	public Adresse_ update(Adresse_ adresse) {

        URI uri = URI.create(adresse.getId().getHref());

        Adresse_DTO adresseDTO = adresseAssembler.toResource(adresse).getContent();

        Adresse_Resource resource = restTemplate.exchange(uri, HttpMethod.PUT, new HttpEntity<>(adresseDTO), Adresse_Resource.class).getBody();

        return adresseAssembler.toBean(resource);
    }
		
	@Override
	public void delete(Link id) {
		URI uri = URI.create(id.getHref());
		restTemplate.exchange(uri, HttpMethod.DELETE, null, Void.class);
	}
}
