package de.muenchen.kvr.buergerverwaltung.buerger.client.rest;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

import de.muenchen.kvr.buergerverwaltung.buerger.client.domain.Sachbearbeiter_DTO;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.Resource;
import org.springframework.hateoas.Resources;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Sachbearbeiter_Resource extends Resource<Sachbearbeiter_DTO> {
	/**
     * This is a simple way to get the Resources "class" for the {@link org.springframework.web.client.RestTemplate#exchange(String, HttpMethod, HttpEntity, ParameterizedTypeReference, Object...)}.
     */
    public static final ParameterizedTypeReference<Resources<Sachbearbeiter_Resource>> LIST = new ParameterizedTypeReference<Resources<Sachbearbeiter_Resource>>() {
    };

    /**
     * Create a new Resource with a blank Sachbearbeiter_DTO.
     */
    public Sachbearbeiter_Resource() {
        super(new Sachbearbeiter_DTO());
    }

    /**
     * Create a new Resource from  a Sachbearbeiter_DTO and multiple Resources.
     * @param content The Sachbearbeiter_DTO
     * @param links The links to add to the resource
     */
    public Sachbearbeiter_Resource(Sachbearbeiter_DTO content, Link... links) {
        super(content, links);
    }

    /**
     * Create a new Resource from  a Sachbearbeiter_DTO and multiple Resources.
     * @param content The Sachbearbeiter_DTO
     * @param links The links to add to the resource
     */
    public Sachbearbeiter_Resource(Sachbearbeiter_DTO content, Iterable<Link> links) {
        super(content, links);
    }
}
