package de.muenchen.vaadin.guilib.security.components;

import de.muenchen.eventbus.selector.entity.ResponseEntityKey;
import de.muenchen.vaadin.guilib.security.components.buttons.listener.Authority_SingleActions;
import de.muenchen.vaadin.guilib.security.services.model.Authority_Datastore;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * Provides a simple {@link Authority_Form} that always shows the {@link Authority_Datastore#getSelectedAuthority()}.
 *
 * @author p.mueller
 * @version 1.0
 */
public class Authority_SelectedForm extends Authority_Form {

    /**
     * Creates a new Authority_Form that updates its Authority_ to the {@link Authority_Datastore#getSelectedAuthority()}
     * from the Eventbus.
     */
    public Authority_SelectedForm() {
        getEventBus().on(new ResponseEntityKey(Authority_Form.ENTITY_CLASS).toSelector(), this::update);
    }
    
    public void reLoad() {
        final Authority_SingleActions singleActions = new Authority_SingleActions(this::getAuthority);
        singleActions.reRead(null);
    }

    /**
     * Update the Authority_ of this Form to the selected one form the DataStore.
     *
     * @param event
     */
    private void update(reactor.bus.Event<?> event) {
        final Authority_Datastore data = (Authority_Datastore) event.getData();
        setAuthority(data.getSelectedAuthority().orElse(null));
    }
}
