package de.muenchen.kvr.buergerverwaltung.buerger.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Buerger_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Buerger_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Buerger_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Buerger_ createBuergerFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Buerger_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Buerger_> createBuergersFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Buerger_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Buerger_> createOptionalBuergerFallback(){
		return Optional.empty();
	}
	
}
