package de.muenchen.kvr.buergerverwaltung.buerger.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Sachbearbeiter_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Sachbearbeiter_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Sachbearbeiter_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Sachbearbeiter_ createSachbearbeiterFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Sachbearbeiter_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Sachbearbeiter_> createSachbearbeitersFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Sachbearbeiter_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Sachbearbeiter_> createOptionalSachbearbeiterFallback(){
		return Optional.empty();
	}
	
}
