package de.muenchen.kvr.buergerverwaltung.buerger.guilib.services;


import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import de.muenchen.kvr.buergerverwaltung.buerger.client.local.Wohnung_;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */
public class Wohnung_FallbackDataGenerator{
	
	/** Fallback-Daten generierung. Diese Methoden werden durch Barrakuda mit dem gewünschten Verhalten befüllt. */
	
	
	/**
	 * Generiert Fallback-Daten für Methoden, die einen einzelnen Wohnung_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Wohnung_ createWohnungFallback(){
		return null;
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die eine Liste von Wohnung_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static List<Wohnung_> createWohnungsFallback(){
		return new ArrayList<>();
	}
	
	/**
	 * Generiert Fallback-Daten für Methoden, die ein Optional von Wohnung_ zurückliefern.
	 * 
	 * @return Generierter fallback-Wert
	 */
	public static Optional<Wohnung_> createOptionalWohnungFallback(){
		return Optional.empty();
	}
	
}
